### ISSUE TITLE
HTTPS bookmarklet doesn't work

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#1]
https://www.archlinux.org/

Try to use bookmarklet there, you'll get 

[19:45:08.332] Blocked loading mixed active content "http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"

**Comment by xekc** [comment]
If you decide to contribute - please keep in mind this task could be also worked at Asana: https://app.asana.com/0/29901823270674/29971396794651 by freefeed.net team (we use Pepyatka). 

It could make sense to reach out to @indeyets or @berkus or drop us a line on freefeed.net@gmail.com to check we don't do the work twice. Thanks!

**Comment by indeyets** [comment]
#100 is related.
we can make it work as long as pepyatka-based website is deployed on https

**Comment by epicmonkey** [comment]
closing, do not care about migration anymore.
