### ISSUE TITLE
/subscribers page is empty

### ISSUE THREAD

**Issue by id** [pepyatka/pepyatka-html#102]
When a user have 1 subscriber (shown in profile), they do not appear on /subscribers page.

Information exists in server response:
subscribers: [{id: "***", username: "test", screenName: "test", type: "user"}]

**Comment by epicmonkey** [comment]
Connected to #92.

**Comment by smallq-git** [comment]
![image](https://cloud.githubusercontent.com/assets/7983303/7228906/6c6d34ea-e766-11e4-9c84-5f6963dec414.png)
