### ISSUE TITLE
upgrade emberjs to latest stable

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#103]
we use `1.11.0-beta.1`, current version is `1.11.1` (there's also beta of 1.12, but it can wait)

**Comment by epicmonkey** [comment]
JFTR: latest ember (1.12) is not really compatible with the latest emder-data (1.0.0-beta.18).

**Comment by indeyets** [comment]
well… at least we can use stable `1.11.3`. makes more sense than shipping with `beta`

**Comment by indeyets** [comment]
If I correctly found the issue, then emberjs/ember.js#11172 (supposedly in 1.12.1) + emberjs/data#3070 (not yet merged) will fix incompatibility

**Comment by epicmonkey** [comment]
Seems the only issue left: https://github.com/emberjs/data/pull/3136 to make application compatible with ember-1.12
