### ISSUE TITLE
Sign up form should disappear after successful sign up

### ISSUE THREAD

**Issue by klera** [pepyatka/pepyatka-html#104]
When user submits sign up form successfully he should see his home feed.

Now he logs in, but stays on a page with sign up form.

![pepyatka-signup1](https://cloud.githubusercontent.com/assets/745423/7157050/8984a18a-e374-11e4-8319-156a2f0c0d11.png)

**Comment by bleysamberite** [comment]
reproduced on fresh Chrome

**Comment by MrGluek** [comment]
same for "sign in" form
