### ISSUE TITLE
Do not show Like link if post has been already liked by current user

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#111]
Right now application shows two links at the same time Like and Un-like post.

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-html/commit/57029abeb9d6e6f440dde6ccdd47afd7d1ea159d

**Comment by smallq-git** [comment]
Only one option is shown at a time
![image](https://cloud.githubusercontent.com/assets/7983303/7332669/79178e48-eb53-11e4-9be1-3754065f62c6.png)
