### ISSUE TITLE
Limit post body to 1500 characters

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#115]
Limit post body to 350 characters to avoid situations like this: https://yadi.sk/d/97tqF_pfg3R47

**Comment by epicmonkey** [comment]
@teinett Please find out in the documentation how many symbols should be shown.

**Comment by teinett** [comment]
Maximum number of characters: 350.

**Comment by klera** [comment]
Maximum number of characters: 350.

**Comment by epicmonkey** [comment]
Thanks. Updated title.

**Comment by berkus** [comment]
We decided to limit post to 1500 graphemes for ff.

**Comment by epicmonkey** [comment]
Updated title

**Comment by smallq-git** [comment]
Can post 1500 symbols now. Line breaks issue: https://github.com/pepyatka/pepyatka-html/issues/639
