### ISSUE TITLE
Parse and highlight URLs in comments

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#118]
If user creates a comment or submits a post that includes link to a web resource like "http://google.com" or "https://google.com" it must become a clickable link. Note that link is everything that start with http:// or https://.

**Comment by epicmonkey** [comment]
This has been already implemented in the master branch and need to be migrated (prettifyText helper)

**Comment by smallq-git** [comment]
@epicmonkey Had this been migrated? I see the same behavior in posts - is this the same bug?
See: https://micropeppa.freefeed.net/#/ivan/e00918a7-3e40-4618-9467-a3788c35d652
![image](https://cloud.githubusercontent.com/assets/7983303/7218921/b8a18604-e68f-11e4-89c1-63a75183ff32.png)

**Comment by epicmonkey** [comment]
Not yet. My comment was a reference to a developer who'll be doing that migration (not to design solution from scratch).

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-html/commit/9f3d973addea2386d530d065c092829af9409142

**Comment by epicmonkey** [comment]
For the record, rules are:
- shorten url if it's nested to more than 2 levels, e.g. http://google.com/a/b
- shorten url after ? symbol e.g. http://google.com/a?123
- shorten url after # symbol e.g. http://google.com/a#123
- shorten url if it's longer than 7 symbols e.g. http://google.com/12345678
