### ISSUE TITLE
In My Discussions page new comment appears only after refresh

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#119]
If user is on My Discussions page and submits a new comment, it won't appear instantly, user will have to refresh page to see it. Note: comments appear fine on other pages like Home feed, User profile, another tab, etc

**Comment by teinett** [comment]
Ожидалось: после добавления комментария форма добавления заменится на только что добавленный мой коммент.

**Comment by ArtyomPetrenko** [comment]
Reproduction:
1. User 1 opens the "My Discussions" page which contains some topic.
2. In the same time User 2 adds a new comment to the topic.
As a result the comment doesn't automatically appear on My Discussions page of User 1 untill the page is manually refreshed.

**Comment by epicmonkey** [comment]
For the reference: My discussion is a materialized timeline that is generated dynamically. As a result it leads to bunch of defects like this one. We need to refactor backend component to handle such timelines better (River of News, My Discussions, custom lists).

**Comment by epicmonkey** [comment]
Pushing to 0.4.0 when migration to postgres is done.

**Comment by teinett** [comment]
Fixed
