### ISSUE TITLE
После выхода из аккаунта стоит вести на главную страницу 

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#121]
сейчас при выходе с сайта я попадаю на страницу входа https://micropeppa.freefeed.net/#/session/signin.

ожидалось: я попаду на https://micropeppa.freefeed.net/

**Comment by epicmonkey** [comment]
Let me kindly disagree with this. FrF behaviour was exactly the same: when you sign out, application will show you a login screen. If there are some other issues, let me know and let's discuss.
