### ISSUE TITLE
Limit username and groupname

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#123]
We need to limit username to 25 characters and groupname to 35 characters. Screenshot: https://yadi.sk/d/wnvwOs58g3U75

**Comment by epicmonkey** [comment]
@teinett Please find out how many characters were allowed in FrF.

**Comment by klera** [comment]
<>  is not a valid display name. Names must be between 3 and 25 characters long.

**Comment by epicmonkey** [comment]
@teinett Do you need help with the documentation?

**Comment by smallq-git** [comment]
@epicmonkey This information is not available in the docs because registration was unavailable when it was created. The only thing we know is that the longest known group name is 35 symbols and longest known username is 25 symbols (according to zverok's archives).

**Comment by epicmonkey** [comment]
Thanks! Updated story. :sunny:

**Comment by smallq-git** [comment]
Correction: username length limit is present in User Settings doc:
https://docs.google.com/document/d/1xKw_MMoU8Bda5N_dRzkDtSbWrymVsSU0edvdW6PfalI/edit?usp=sharing
