### ISSUE TITLE
Email should be saved when user updates his settings

### ISSUE THREAD

**Issue by klera** [pepyatka/pepyatka-html#124]
UPD:
Email should be saved when user updates his settings.

Now submitted in settings email is not saved. 
When user submits settings form - email just disappears.

When user opens his settings page, he should see his actual info filled into the form as default.
![image](https://cloud.githubusercontent.com/assets/745423/7184809/d867af7e-e467-11e4-9282-58184b8b9ebe.png)

Now user has email field empty.

**Comment by berkus** [comment]
Did you set your email?

**Comment by klera** [comment]
No ) 

Ok,  issue: submitted email in settings is not saved.
