### ISSUE TITLE
Clear sign in/sign up fields are form is submitted

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#125]
This is a potential security issue. Clear sign in/sign up fields are form is submitted.

**Comment by smallq-git** [comment]
1. Go to Sign In page
2. Enter username and incorrect password -> error is displayed.
3. Go to Sign Up page.
4. Create a new user.
5. Log out.
6. Go to Sign In page

Expected: Form is clear slate.
Actual: Form contains previously entered information and displays the error.
