### ISSUE TITLE
Rename link "Destroy" to "Delete"

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#126]
Screenshot: https://yadi.sk/d/cLo3GQ-kg3UfM

**Comment by berkus** [comment]
This is merged, closing.

**Comment by smallq-git** [comment]
Verified on test server:
![image](https://cloud.githubusercontent.com/assets/7983303/7599552/b2023666-f90b-11e4-95aa-86371fc916a5.png)
