### ISSUE TITLE
It is not possible to upload image larger than 1MB

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#129]
User should be able to attach files up to 20MB

**Comment by id** [comment]
Should be fixed by https://github.com/pepyatka/pepyatka-server/pull/178

**Comment by smallq-git** [comment]
Verified:
![image](https://cloud.githubusercontent.com/assets/7983303/7332642/8379b55c-eb51-11e4-9885-b4a233de99c4.png)

**Comment by teinett** [comment]
I can't attach file to Freefeed account. 
- Click Choose button
- Choose the file on Open dialog
- Click Open button

Nothing happens.

Expected: I will see progress of attaching and preview of the image before posting.

**Comment by teinett** [comment]
I can't attach file https://yadi.sk/d/ubLbesFrgSMCc to Freefeed account. 
- Click Choose button
- Choose the file on Open dialog
- Click Open button

Nothing happens.

Expected: I will see progress of attaching and preview of the image before posting.

**Comment by id** [comment]
Works on micropeppa: https://micropeppa.freefeed.net/ivan/8501ef3a-1f50-48f3-8072-7e9dc98e10d4

**Comment by clbn** [comment]
@id
We discussed it with @teinett, it was a problem with internet connection, so it was related to #332. This one should remain closed.
