### ISSUE TITLE
Cannot add pictures and thumbnail is not displayed when adding pictures from own feed or discussions

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#131]
1. While on own feed's page or on Discussions page, Choose File and select picture.
2. Click Open.

**Expected**: Picture added and thumbnail is displayed, like it happens on homefeed page:
![image](https://cloud.githubusercontent.com/assets/7983303/7201883/3120a2f8-e515-11e4-8f13-bc8c87894bb6.png)

![image](https://cloud.githubusercontent.com/assets/7983303/7201901/60f90448-e515-11e4-8b6d-64aa6aece0b8.png)

**Actual**: Only filename is displayed. When post is saved, it's saved without the picture:

![image](https://cloud.githubusercontent.com/assets/7983303/7201905/6ae8416c-e515-11e4-9443-ba3f7a948853.png)

**Comment by teinett** [comment]
Пост с этой картинкой в моем профайле отобразился без картинки - https://yadi.sk/d/QDYAlo-Ag3VkH
При добавлении ровно той же самой картинки через домашюю страницу картинка добавилась - https://yadi.sk/d/pkxELrcOg3VqG

**Comment by teinett** [comment]
Аналогично на странице https://micropeppa.freefeed.net/#/filter/discussions - картинки не добавляются.

**Comment by smallq-git** [comment]
Appears to be fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/7310193/85100910-ea30-11e4-94f7-267669f8ba04.png)
