### ISSUE TITLE
On own feed's page there are two Settings links (one incorrect)

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#133]
1. Log in and view own feed.

Expected:
1. Edit Profile link next to profile picture in the main area (leads to Edit Profile popup)
2. Settings link below display name in the sidebar (leads to Edit Settings page)

![image](https://cloud.githubusercontent.com/assets/7983303/7201803/351ac6e6-e514-11e4-91b7-f4f59f2663fc.png)

Actual: Two Settings links are displayed. The one in main area leads to homefeed (https://micropeppa.freefeed.net/#). 
The one on the side bar is correct (leads to https://micropeppa.freefeed.net/#/settings).

![pepyatka 2015-04-16 19-01-10](https://cloud.githubusercontent.com/assets/11980339/7185650/b06a5828-e46c-11e4-8ae5-69a8f30a96a3.jpg)

**Comment by brain-1** [comment]
Тут же в своем фиде линки на Unsubscribe / Subscribe - их не должно быть

**Comment by teinett** [comment]
Связано с https://github.com/pepyatka/pepyatka-html/issues/132

**Comment by kappa** [comment]
Не могу воспроизвести битую ссылку. Обе одинаковые и обе работают.

**Comment by epicmonkey** [comment]
This issue has been resolved in https://github.com/pepyatka/pepyatka-html/pull/199
