### ISSUE TITLE
Limit screenName to 25 characters

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#134]
Screenshot: https://yadi.sk/d/rlgxWR_Fg3Wmq

**Comment by epicmonkey** [comment]
@teinett Please clarify limits to screenName.

**Comment by klera** [comment]
Names must be between 3 and 25 characters long.

**Comment by epicmonkey** [comment]
Thanks. Update story.

**Comment by indeyets** [comment]
this one was fixed last week

**Comment by epicmonkey** [comment]
In fact, error messages wasn't updated. Tho' there is a big story to do this: https://github.com/pepyatka/pepyatka-html/issues/271
