### ISSUE TITLE
Posts does not wrap comments to a link "more N comments"

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#135]
Link: https://micropeppa.freefeed.net/#/

Screenshot: https://yadi.sk/d/zp0woL9wg3Wu5

**Comment by epicmonkey** [comment]
Dup of https://github.com/pepyatka/pepyatka-html/issues/14

**Comment by smallq-git** [comment]
Since https://github.com/pepyatka/pepyatka-html/issues/14 was closed, I'm re-opening this one as actual:
![image](https://cloud.githubusercontent.com/assets/7983303/7302978/f6ccb638-e9f5-11e4-9950-88b3bfd3f0f5.png)

**Comment by epicmonkey** [comment]
Promoted in https://github.com/pepyatka/pepyatka-html/commit/b44a413d5d0b6d3904e8b8aabb8f0bc5612c6989. Though it's not completely tested against real-time events.

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-html/commit/f8ad85e. However please note that there is one outstanding issue left: https://github.com/pepyatka/pepyatka-html/issues/21

**Comment by epicmonkey** [comment]
Reopening. When user is on one post page and expands comments and follows to timeline with that post expanded comments are missing.

**Comment by smallq-git** [comment]
Comments are folding now:
![image](https://cloud.githubusercontent.com/assets/7983303/7878312/24ccdd38-05ee-11e5-81b0-55a76cdeb108.png)

Albeit not in real-time (separate issue for that https://github.com/pepyatka/pepyatka-html/issues/420).
Last two comment are also not shown when commenting (https://github.com/pepyatka/pepyatka-html/issues/21).
