### ISSUE TITLE
Long comments not collapsed to "more" link

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#136]
Pre-Condition: user has comments longer than 512 symbols (https://micropeppa.freefeed.net/#/teine)
1. From homefeed or user feed view post with long comment.

Expected: Long comment is collapsed to 502 symbols, the rest is hidden under "more" link
![image](https://cloud.githubusercontent.com/assets/7983303/7201752/83e0135e-e513-11e4-9399-be46cea341e4.png)

Actual: Long comment is displayed in its entirety.
![image](https://cloud.githubusercontent.com/assets/7983303/7201757/90c744a2-e513-11e4-91b7-b7ba068800eb.png)

**Comment by epicmonkey** [comment]
Note: this function has been already implemented in master branch and called "prettifyText".

**Comment by smallq-git** [comment]
From OnePost description:

On a feed page, if the length of the comment text is more than 512 characters it will appear truncated. Only first 502 characters will be shown, the rest becomes visible after clicking on “more...” shortcut.
First comment of the post is always displayed entirely regardless of it’s length. On a single post page, the comment texts are never truncated.
