### ISSUE TITLE
Cannot create a group - no link

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#138]
Link "Browse/edit groups" on the right panel open https://micropeppa.freefeed.net/#/groups page, but it's empty.

Screenshot: https://yadi.sk/d/UX7hjLypg3XUT

There is no link to create a group on the website

**Comment by epicmonkey** [comment]
Dup of https://github.com/pepyatka/pepyatka-html/issues/45

**Comment by epicmonkey** [comment]
There is one more case to cover. Re-opening.
