### ISSUE TITLE
Recipient text field (To: field) is not displayed but Add/Edit link is hidden on click

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#140]
1. While on homefeed page position cursor in post creation text field -> To: field is displayed with Add/Edit link next to it.

![image](https://cloud.githubusercontent.com/assets/7983303/7201560/38e48148-e511-11e4-853d-70b578eed6ae.png)

2. Click Add/Edit link.

Expected: link is hidden, text field is opened, allowing for selection of recipients.
Actual: link is hidden, no text field is visible.

![image](https://cloud.githubusercontent.com/assets/7983303/7201581/6e3edcd0-e511-11e4-9fb0-4a0c57d80330.png)

**NOTE**: The field is there but not visible.

![image](https://cloud.githubusercontent.com/assets/7983303/7201589/90208bfa-e511-11e4-807c-5753c19137b5.png)

**Comment by smallq-git** [comment]
Defect is fixed, UI improvements in https://github.com/pepyatka/pepyatka-html/issues/296

**Comment by smallq-git** [comment]
It's back: 
![image](https://cloud.githubusercontent.com/assets/7983303/8015937/1641861c-0be6-11e5-8e9f-a6c9ea09375d.png)

**Comment by epicmonkey** [comment]
okay, we can close this one now.

**Comment by smallq-git** [comment]
Verified in Chrome:
![image](https://cloud.githubusercontent.com/assets/7983303/9152549/0f724ee8-3e36-11e5-9dcd-baae105e9df7.png)
