### ISSUE TITLE
On home page only 25 posts per page, not 30

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#142]

**Comment by epicmonkey** [comment]
This is not true. FrF was showing 25 posts per page.

**Comment by klera** [comment]
It is true, all feeds should have 30 posts per page. 
Lists of subscribers - 72 items per page.
Actual numbers can be found in URI schema description  https://docs.google.com/document/d/1kV9TZOPnG7sxM9rbHQc3-8nbnrzc17wTYpARhkNy99I/edit

**Comment by epicmonkey** [comment]
Gotcha!

**Comment by smallq-git** [comment]
Works for homefeed, user's feed and probably would've worked for Discussions if not for https://github.com/pepyatka/pepyatka-html/issues/383 :-E
