### ISSUE TITLE
Can't see post creation timestamp.

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#145]
No tooltip is displayed on mouseover on relative time info.

1. On any feed or post page hover mouse over "A day/minute ago" information on a post.

Expected: a tooltip with information about when the post was created (time and date).
Actual: nothing happens.

Example post: https://micropeppa.freefeed.net/#/test/ae3426b2-95c5-4f8e-9da5-96eca7b2040a 

![image](https://cloud.githubusercontent.com/assets/7983303/7201138/aef88da2-e50c-11e4-96d4-ac1354b33a08.png)

**Comment by smallq-git** [comment]
This only works from individual post page. When I hover mouse in timeline, no popup appears.

**Comment by epicmonkey** [comment]
Gosh. Thanks.

**Comment by smallq-git** [comment]
Now works.
Separate issue created for more humane display: https://github.com/pepyatka/pepyatka-html/issues/470
