### ISSUE TITLE
Клик на логотип приводит на N-ную страницу домашнего фида

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#146]
Была в посте https://micropeppa.freefeed.net/#/test/ae3426b2-95c5-4f8e-9da5-96eca7b2040a
Кликнула на логотип
Попала на страницу https://micropeppa.freefeed.net/#/?offset=25
Ожидалось: попаду на домашнюю страницу https://micropeppa.freefeed.net/

**Comment by brain-1** [comment]
дубль https://github.com/pepyatka/pepyatka-html/issues/144

**Comment by epicmonkey** [comment]
dup of #144.
