### ISSUE TITLE
Pages are not opened when links are clicked

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#147]
Sometimes the site stops reacting to clicks. 
Video: https://yadi.sk/i/Pkkz0s3jg3ZPc

[smallq]: Header link and sidebar links are definitely affected. For some reason Settings and Groups are always working. The problem goes away after F5.

**Comment by epicmonkey** [comment]
For the reference: most likely the problem is in the code (timeline controllers):
```
  postSortProperties: ['createdAt:desc'],
  allPosts: Ember.computed.sort('model.posts', 'postSortProperties'),
```
per https://github.com/emberjs/ember.js/issues/10343.

Though Ember.computed.sort is a nice helper we can replace it to:
```
posts: function() {
  return Ember.ArrayProxy.createWithMixins(Ember.SortableMixin, {
    sortProperties: ['createdAt'],
    sortAscending: false,
    content: this.get('content.posts')
  })
}.property('content.posts'),
```

**Comment by smallq-git** [comment]
do not see this anymore.
