### ISSUE TITLE
Personal feed displays number of likes incorrectly

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#148]
Wrong number is displayed in user profile as number of user's likes

"X likes" should display the number of posts user liked.
Instead, it displays the number of user's posts that were liked by other people (including self-likes).

![](https://cloud.githubusercontent.com/assets/7983303/7200719/5c8b6a34-e508-11e4-8c32-e63eb7c7361d.png)

**Comment by smallq-git** [comment]
Wrong number is displayed in user profile as number of user's likes

"X likes" should display the number of posts user liked.
Instead, it displays the number of user's posts that were liked by other people (including self-likes).

![image](https://cloud.githubusercontent.com/assets/7983303/7200719/5c8b6a34-e508-11e4-8c32-e63eb7c7361d.png)
