### ISSUE TITLE
It should be possible to complete the post by Cmd-Enter/Ctrl-Enter

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#149]
Currently (as of 2015-04-16) after typing in the post you need to click on a Post button (by mouse or by navigating with Tab to it). It's OK to treat Enter key as new paragraph, but let's make Cmd-Enter (Ctrl-Enter on Windows) to actually post the text (same as on Facebook).

**Comment by earlyadopter** [comment]
Update: in Safari you couldn't even use Tab to navigate to a Post button.

**Comment by epicmonkey** [comment]
Dup of https://github.com/pepyatka/pepyatka-html/issues/114
