### ISSUE TITLE
Does not show Like and Un-like links at the same time

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#151]
If we're allowing to like your own post, "Like" link for a liked post should be replaced with "Unlike" (and act accordingly). Currently (as of 2015-04-16) it remains intact, and does nothing after used once.

**Comment by earlyadopter** [comment]
Update: for a post which wasn't liked yet we're showing (Un-like) link which does nothing.

**Comment by epicmonkey** [comment]
For the time being it's a feature :sunny:. However I'm leaving this story to fix Like and Un-like links.

**Comment by smallq-git** [comment]
Same goes for Subscribe/Unsubscribe in other user's profile.

**Comment by epicmonkey** [comment]
Resolved two tasks:
- do not show Like and Un-like links at the same time
- do not show Subscribe and Unsubscribe links at the same time.

**Comment by smallq-git** [comment]
Now either Like or Un-Like link is displayed at one time:
![image](https://cloud.githubusercontent.com/assets/7983303/7332655/e37051c2-eb52-11e4-9516-2b4c7696bcac.png)
