### ISSUE TITLE
"Hide" hides post instantly and doesn't give an option to undo

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#152]
"Hide" works instantly and doesn't give an option to undo
- In a feed click Hide button

Expected: Post is collapsed, message is displayed: "Entry hidden **undo** or **hide other items like this one**" where "undo" and "hide other items like this" are links to announced actions.
Actual: Post disappears with no option to undo an erroneous action.

Video: https://yadi.sk/d/yvp5cKXNg3byQ

**Comment by smallq-git** [comment]
"Hide" works instantly and doesn't give an option to undo

# In a feed click Hide button

Expected: Post is collapsed, message is displayed: "_Entry hidden_ undo or hide other items like this one" where "undo" and "hide other items like this" are links to announced actions.
Actual: Post disappears with no option to undo an erroneous action.

Video: https://yadi.sk/d/yvp5cKXNg3byQ

**Comment by teinett** [comment]
Fixed
