### ISSUE TITLE
Cleaner URL wanted (no # between the domain and user name)

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#154]
Currently (2015-04-16) clicking on my own username brings a page with URL https://micropeppa.freefeed.net/#/earlyadopter

Can we please remove # from the URL? Manual removal brings 404 error.

**Comment by teinett** [comment]
Каждый спрашивает про это # - да, его уберут, это дубль задачи, только не помню какой. :)
