### ISSUE TITLE
Cannot attach .txt or .mp3 file to a post.

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#155]
Behavior differs when in own feed and on home feed page.

**On home feed page**
Video: https://yadi.sk/d/5g2NTWv8g4Jg9
1. Click Choose File.
2. Select .txt or .mp3 file to add.
3. Click Open -> window is closed.

Expected: File is attached to the post, file name is displayed next to Choose File button.
Actual: File is not attached, file name is not displayed.

**On own feed's page**
Possibly related to #131
Video: https://yadi.sk/d/PWBRPTcfg4JM2
1. Click Choose File.
2. Select .txt or .mp3 file to add.
3. Click Open -> window is closed, file name is displayed next to the Choose File button.
4. Enter post text, click Post.

**Expected**: post is saved and displayed, file is attached and can be downloaded. Area next to Choose File button is cleared.
**Actual**: Post is saved is displayed without the file. File name is displayed next to Choose File button.

![image](https://cloud.githubusercontent.com/assets/7983303/7200316/81abd398-e504-11e4-9f51-7ea2f4540991.png)

**Comment by smallq-git** [comment]
Cannot attach a .txt file to a post.
Different behavior when in own feed and on home feed page.

*On home feed page*
Video: https://yadi.sk/d/5g2NTWv8g4Jg9
1. Click Choose File.
2. Select .txt file to add.
3. Click Open -> window is closed.

Expected: File is attached to the post, file name is displayed next to Choose File button.
Actual: File is not attached, file name is not displayed.

*On own feed's page*
Video: https://yadi.sk/d/PWBRPTcfg4JM2
1. Click Choose File.
2. Select .txt file to add.
3. Click Open -> window is closed, file name is displayed next to the Choose File button.
4. Enter post text, click Post.

Expected: post is saved and displayed, file is attached and can be downloaded. Area next to Choose File button is cleared.
Actual: Post is saved is displayed without the file. File name is displayed next to Choose File button.

![image](https://cloud.githubusercontent.com/assets/7983303/7200316/81abd398-e504-11e4-9f51-7ea2f4540991.png)

**Comment by clbn** [comment]
@epicmonkey You can assign this one to me.

I'm going to add support for non-image files soon. (Right now, no promises about mp3-player etc, but it should be possible to attach any file.)

**Comment by epicmonkey** [comment]
Sure thing. Just for the record there is a story https://github.com/pepyatka/pepyatka-html/issues/83 that potentially leads to bunch of defects. As for mp3-player there is another story: https://github.com/pepyatka/pepyatka-html/issues/77

**Comment by epicmonkey** [comment]
Resolved in 484c4c32edb9267d292a910e5dd84ba12f0be3f0
