### ISSUE TITLE
All posts have the same title - <title>Pepyatka</title>

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#156]
All posts have the same title tag: Pepyatka.

Expected: every post's individual page has title unique to this post, e.g.: "%first N symbols of the post% - Pepyatka".
Actual: every post page has the same title: Pepyatka.

![](https://cloud.githubusercontent.com/assets/7983303/7200190/3536012e-e503-11e4-8fef-a60393c100c4.png)

**Comment by smallq-git** [comment]
All posts have the same title tag:  <title>Pepyatka</title>.

Expected: every post's individual page has title unique to this post, e.g.: "%first N symbols of the post% - FreeFeed".
Actual: every post page has the same title: <title>Pepyatka</title>.

![image](https://cloud.githubusercontent.com/assets/7983303/7200190/3536012e-e503-11e4-8fef-a60393c100c4.png)

**Comment by urbansheep** [comment]
I deem this important enough to consider adding sometime in 0.4.\* release schedule.

**Comment by indeyets** [comment]
@urbansheep would you be able to create a spec for this?

**Comment by berkus** [comment]
Technically it's easy to change (see http://stackoverflow.com/questions/13588523/setting-page-title-with-ember-js)

We only need a spec of what to show (similar to current breadcrumbs titles we can add that to controllers easily), my estimate would be <1 man-hour .

**Comment by urbansheep** [comment]
Home:
`FreeFeed`

Pager sub-element (added to other titles):
`— Page [number]`

User:
`([number of unread posts]) [Display Name] ([Username]) [pager] — FreeFeed`

Group:
`([number of unread posts]) [Display Name] ([Groupname]) [pager] — FreeFeed`

Direct Messages:
`([number of unread posts]) Direct Messages [pager] — FreeFeed`

Post:
`([number of unread comments]) [Post text, max 60 chr] — [Display Name] ([Username]) — FreeFeed`

Number of unread items is prepended when current view has been updated without user seeing new content (no focus to the current tab/window), similar to what GMail/FB does for new notifications.

**Comment by teinett** [comment]
Fixed
