### ISSUE TITLE
Clicking on Subscribe link on somebody's page should not bring an empty page.

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#159]
I don't remember what was happening in Fiendfeed when you subscribed to someone's feed, but it definitely wasn't a relatively empty page. My expectation (what seams logical) would be to make "Subscribe" link either disappear, or became a greyed out label (not a link) or become an "Unsubscribe" link.

**Comment by indeyets** [comment]
Friendfeed redirected to the home-feed, Pepyatka shows `/about` which looks empty

**Comment by klera** [comment]
Friendfeed did not any redirect after subscription. 

When user subscribes to a feed - he should stay on the same page after subscription. (and choose lists for the feed he subscribed to in pop-up)

**Comment by epicmonkey** [comment]
This is a dup of https://github.com/pepyatka/pepyatka-html/issues/112. Closing.
