### ISSUE TITLE
Скорость загрузки сайта - Enable compression

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#160]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmicropeppa.freefeed.net

Compressing resources with gzip or deflate can reduce the number of bytes sent over the network.
Enable compression for the following resources to reduce their transfer size by 829.4KiB (74% reduction).
Compressing https://micropeppa.freefeed.net/js/config.js?v=v1 could save 755.2KiB (73% reduction).
Compressing https://micropeppa.freefeed.net/js/main.js?v=v1 could save 63.5KiB (85% reduction).
Compressing https://micropeppa.freefeed.net/js/libs/requirejs/2.1.15/require.min.js could save 8.8KiB (59% reduction).
Compressing https://micropeppa.freefeed.net/js/app/main.js?v=v1 could save 2KiB (77% reduction).

**Comment by epicmonkey** [comment]
It has nothing to do with a technical platform. Closing as won't fix.

**Comment by indeyets** [comment]
@epicmonkey why? "technical platform" can support generation of gzipped resources

**Comment by epicmonkey** [comment]
This is usually done by a web-server, eg nginx. Good point to document this in wiki, however it's not something we'll do in the code.

**Comment by epicmonkey** [comment]
On the second thought. We have pepyayka-ansible project that could do this.
