### ISSUE TITLE
Скорость загрузки сайта - Minify JavaScript

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#161]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmicropeppa.freefeed.net

Compacting JavaScript code can save many bytes of data and speed up downloading, parsing, and execution time.
Minify JavaScript for the following resources to reduce their size by 93.4KiB (9% reduction).
Minifying https://micropeppa.freefeed.net/js/config.js?v=v1 could save 78.8KiB (8% reduction).
Minifying https://micropeppa.freefeed.net/js/main.js?v=v1 could save 14.6KiB (20% reduction).

**Comment by indeyets** [comment]
site works in debug-friendly mode. production mode will use minifying, obviously
