### ISSUE TITLE
List of post likers displaynames should be separated with commas.

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#163]
List of users who "liked" a post should be separated by commas and limited to the first 5 "likers". The rest should be hidden behind "and X other users liked this post" where "X other users" is a link exposing the full list.

If there are less than 5 "likers", they should be listed with commas as separators and "liked this post" text behind the list, like so:

"X, Y and Z liked this post" where X, Y and Z are links to "likers" feeds.

Current view (There are exactly 3 likers but it's difficult to read!): 

![](https://cloud.githubusercontent.com/assets/7983303/7200060/0b7b04c0-e502-11e4-8b32-f9a231735f5d.png)

**Comment by smallq-git** [comment]
List of users who "liked" a post should be separated by commas and limited to the first 5 "likers". The rest should be hidden behind "and X other users liked this post" where "X other users" is a link exposing the full list.

If there are less than 5 "likers", they should be listed with commas as separators and "liked this post" text behind the list, like so:

"X, Y and Z liked this post" where X, Y and Z are links to "likers" feeds.

Current view (There are exactly 3 likers but it's difficult to read!): 
![image](https://cloud.githubusercontent.com/assets/7983303/7200060/0b7b04c0-e502-11e4-8b32-f9a231735f5d.png)

**Comment by epicmonkey** [comment]
@slider23 I've pushed a little better version in https://github.com/pepyatka/pepyatka-html/commit/9cab3e3, though it still needs to be improved .

**Comment by epicmonkey** [comment]
Created a new story to improve styling: https://github.com/pepyatka/pepyatka-html/issues/288. Closing this one.
