### ISSUE TITLE
Скорость загрузки сайта - поставить дату expire для статичных файлов

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#164]
http://www.webpagetest.org/result/150416_07_13XF/1/performance_optimization/#cache_static_content - сейчас статичный контент никак не кешируется

**Comment by epicmonkey** [comment]
It has nothing to do with a technical platform. Closing as won't fix. Could be documented in wiki though.

**Comment by indeyets** [comment]
@epicmonkey why? "technical platform" can support generation of gzipped resources
