### ISSUE TITLE
Добавить счетчик Яндекс.Метрики

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#166]

**Comment by indeyets** [comment]
wrong project

**Comment by indeyets** [comment]
wrong project

**Comment by clbn** [comment]
@indeyets How is it wrong?

**Comment by epicmonkey** [comment]
Pepyatka is a technical platform, it has nothing to do with micropeppa.

**Comment by indeyets** [comment]
@clbn this is a bugtracker of opensource "pepyatka" project, but the task is about `freefeed.net` website. it is not even about testing-site

**Comment by clbn** [comment]
I would agree with a comment, like, "Irrelevant" or "Pepyatka != Micropeppa".

But "wrong project" implies there is a "right project" somewhere, so it looks like it has to be moved to `pepyatka-server` (the only "other" project here). It was too confusing! TOO! CONFUSING!
