### ISSUE TITLE
"Home" on an after-subscribe page has a wrong URL

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#170]
After clicking Subscribe link on somebody's else page an "empty" page is displayed (with regular links to Home, etc.) "Home" link on that "empty" page has URL domain/#/about, not domain/my_own_username.

**Comment by epicmonkey** [comment]
Isn't it dup of https://github.com/pepyatka/pepyatka-html/issues/112?

**Comment by epicmonkey** [comment]
Closing as a duplicate of #112.
