### ISSUE TITLE
Password is optional on Sign Up form

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#176]
1. Open Sign Up page https://micropeppa.freefeed.net/#/users/signup
2. Enter username.
3. Click "Sign Up" button.

Expected: error is displayed "Please enter your password".
Actual: user is logged in.

![image](https://cloud.githubusercontent.com/assets/7983303/7199886/c4cc3e6e-e500-11e4-8e2b-08f50b8293d9.png)

**Comment by epicmonkey** [comment]
Love that one! :sunglasses: Have you ever wanted to create a single-use account that you won't be able to login after your session expired or you logout?

**Comment by epicmonkey** [comment]
Resolved in the backend: https://github.com/pepyatka/pepyatka-server/pull/161

**Comment by smallq-git** [comment]
No longer reproduced: now message is displayed: "Error: Password cannot be blank"

![image](https://cloud.githubusercontent.com/assets/7983303/7228817/bdb96ce8-e765-11e4-9579-2cf4738078a2.png)
