### ISSUE TITLE
When creating a new post - don't see name of feed

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#177]
![pepyatka 2015-04-17 14-19-44](https://cloud.githubusercontent.com/assets/11980339/7201154/d92cff40-e50c-11e4-8814-de7ecccf43d2.jpg)

**Comment by smallq-git** [comment]
Related: #140

**Comment by epicmonkey** [comment]
@slider23 I'm assigning #177 and #140 to you. Functional part is done in #201, though sadly it does nothing to UI.

**Comment by smallq-git** [comment]
@epicmonkey @slider23 I now see the feed name in the post box. Is there anything else planned for this issue?

![image](https://cloud.githubusercontent.com/assets/7983303/7309975/ca3cddb8-ea2d-11e4-8113-c731857b85b4.png)

**Comment by epicmonkey** [comment]
Styling is rather ugly -- we could improve it.

**Comment by smallq-git** [comment]
Created a new ticket for styling: https://github.com/pepyatka/pepyatka-html/issues/296
