### ISSUE TITLE
[REOPEN] When browsing feed history, post creation form should not be displayed, Older/Newer should be on top and bottom

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#180]
0. Pre-Condition: enough posts in homefeed for Older Items link to appear.
1. Scroll down and click Older Items link -> you are on ?offset=25 page.

Expected: post creation form is not displayed; links to view Older/Newer items are displayed at the top and at the bottom.
Actual:  post creation form is present; Older/Newer Items links are only at the bottom.

![image](https://cloud.githubusercontent.com/assets/7983303/7201457/fef94f96-e50f-11e4-96a4-efbd44026f50.png)

**Comment by smallq-git** [comment]
split from #143

**Comment by smallq-git** [comment]
this is NOT fixed: 
![image](https://cloud.githubusercontent.com/assets/7983303/7227295/4bb3dd0c-e758-11e4-8c1f-41d03f560d9b.png)

**Comment by epicmonkey** [comment]
True. Closed by mistake wrong story. Thanks.

**Comment by epicmonkey** [comment]
Well... wait a moment.

**Comment by epicmonkey** [comment]
There are two issues:
- do not display form on 2+ pages
- show pagination at the top and at the bottom.

Which one was not fixed?

**Comment by smallq-git** [comment]
@epicmonkey Both are not fixed on homefeed. Screenshot was taken on page 2 of the homefeed. Post form is still present, Older/Newer links are absent at the top (present at the bottom).

**Comment by smallq-git** [comment]
@epicmonkey 
p1 confirmed as fixed: no post form on homefeed or user's individual feed.
p2 is NOT fixed: there are no pagination at the top of the page.
Individual user's page:
![image](https://cloud.githubusercontent.com/assets/7983303/7228151/1032c8f4-e75f-11e4-9a9a-71fa3e5f5887.png)

**Comment by epicmonkey** [comment]
I can be wrong, but top pagination is displayed only if user is on 2+ page?

**Comment by smallq-git** [comment]
Verified:
![image](https://cloud.githubusercontent.com/assets/7983303/7287700/4424e0d6-e960-11e4-962d-957dd9e24d6d.png)

New issue opened for wordy but incurious user: https://github.com/pepyatka/pepyatka-html/issues/240
