### ISSUE TITLE
The option "Change password" in Settings menu doesn't work

### ISSUE THREAD

**Issue by wordenhh** [pepyatka/pepyatka-html#184]

**Comment by wordenhh** [comment]
Nothing happens when the user press "Update Password" button.

**Comment by epicmonkey** [comment]
Could you check if it does not work (ie does not update password) or does not show any info/error messages? Thanks.

**Comment by wordenhh** [comment]
Checked. The password was actually changed, only there was no confirmation (or any kind of reaction).

http://prntscr.com/6uvtmr

Browser: Chrome.

**Comment by epicmonkey** [comment]
Gotcha. I'll update and prioritise story later today.

**Comment by brain-1** [comment]
In Safari error console:
[Error] Failed to load resource: the server responded with a status of 422 (Bad Request) (updatePassword, line 0) https://micropeppa.freefeed.net/v1/users/updatePassword

**Comment by epicmonkey** [comment]
@brain-1 can you please verify server response and also tell me what currentPassword, newPassword and passwordConfirmation you was using?

**Comment by brain-1** [comment]
Right now all is working
