### ISSUE TITLE
Likes don’t collapse to link «and N other people liked this»

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#186]
Example: https://micropeppa.freefeed.net/#/teine/01462e0b-e782-43b7-8f64-fd6761ae0c86

Screenshots:
https://yadi.sk/d/eaByJsiKg4u9u - one post’s page
https://yadi.sk/d/cBPSIG2Qg4uCk - one user’s page
https://yadi.sk/d/_iZlh1IZg4uEc - home page

Expected:
![2015-04-17 19-40-29](https://cloud.githubusercontent.com/assets/1038168/7208914/a8cd7ef2-e54c-11e4-903b-80dc041b5f50.png)

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-html/issues/24

**Comment by smallq-git** [comment]
Collapsed now:
![image](https://cloud.githubusercontent.com/assets/7983303/7332591/f716e0f0-eb4e-11e4-8705-f6d2e7daf00e.png)
