### ISSUE TITLE
Add +1 to Like each click to link "Like" 

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#206]
Before:
![pepyatka 2015-04-20 11-05-55](https://cloud.githubusercontent.com/assets/11980339/7226034/551d5c84-e74d-11e4-9dc3-c797ccd25c61.jpg)
After 10 click to link Like:
![pepyatka 2015-04-20 11-07-30](https://cloud.githubusercontent.com/assets/11980339/7226059/83667e68-e74d-11e4-96f9-51f8343d9f87.jpg)

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-server/issues/152 (once server issue is resolved it won't happen in the frontend)

**Comment by smallq-git** [comment]
No longer reproduced (can't like a post more than once)
