### ISSUE TITLE
Post comment/post on Enter

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#207]
Right now we don't have any way to post from keyboard at all. Frf had Enter as trigger for comment/post/edit posting. We should either use Enter for this or Ctrl+Enter.

Note: If we use Ctrl+Enter, we are breaking Frf specialty: long posts posted as paragraphs in comments. I suggest we keep Enter as post trigger.

**Comment by epicmonkey** [comment]
Dup of #139 and #114 -- two stories to submit post and comment on Enter.
