### ISSUE TITLE
Show two last comments

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#21]
If comments block is collapsed and application renders a new comment, it should be rendering two last comments instead. Also connected to #50 and #52.

**Comment by mantycore** [comment]
Попробую разобраться в этом и связанных — https://github.com/pepyatka/pepyatka-server/issues/50, https://github.com/pepyatka/pepyatka-server/issues/52, #13

**Comment by berkus** [comment]
@mantycore есть прогресс?

**Comment by epicmonkey** [comment]
Closing per linked story.
