### ISSUE TITLE
No username displayed in /subscribers for some users (intermittent)

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#211]
ETA: reproduced for other users as well (see screenshot in comments)

1. Subscribe to user manyposts (https://micropeppa.freefeed.net/#/manyposts)
2. Go to Browser/Manage friends (https://micropeppa.freefeed.net/#/YOUR USER/subscriptions)

Expected: all users are displayed as profile picture + username.
Actual: for user manyposts only profile picture placeholder is displayed.
Reproduced for users testo and newuser1/newuser1

![image](https://cloud.githubusercontent.com/assets/7983303/7229237/0bb0f67e-e76a-11e4-935a-aab06b76886e.png)

**Comment by smallq-git** [comment]
Looks like it's not limited to manyposts:

![image](https://cloud.githubusercontent.com/assets/7983303/7230281/e3d97dfa-e774-11e4-8f9b-9ab7e87ed492.png)

**Comment by epicmonkey** [comment]
FTR: we need to review Subscriber, Subscription, User, and Timeline serializers in the backend and Subscriber, Subscription, User, and Timeline models in the frontend.

**Comment by epicmonkey** [comment]
Should be resolved after https://github.com/pepyatka/pepyatka-html/commit/d30b807d6c8f4ae87d38ca187af70c16d9215b99

**Comment by epicmonkey** [comment]
Two use cases two verify:
- user opens main page, then clicks on username, then opens "subscriptions"
- user opens her browser right on "subscriptions" page.

**Comment by smallq-git** [comment]
Both cases work now.
