### ISSUE TITLE
Email field in User Settings is not validated

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#213]
1. Log in.
2. Open Settings (https://micropeppa.freefeed.net/#/settings)
3. Enter gibberish into Email field.
4. Click Update button.

Expected: error message (depending on the type of gibberish)
Actual: no errors, information is saved and displayed.

![image](https://cloud.githubusercontent.com/assets/7983303/7229710/7447e3a0-e76f-11e4-8dcc-e2630cac2361.png)

**Comment by epicmonkey** [comment]
JFTR: email IS validated, though application is silent if there any validation errors.

**Comment by smallq-git** [comment]
If email is validated, then why invalid email is saved? I assumed that
failed validation means not saving the data...

**Comment by epicmonkey** [comment]
No doubt that you refreshed Setting page by F5, however could you do a favor and check this one more time? Just a remark, that when you click on "Update" with an invalid email application won't show any error messages and you'll need to manually refresh a webpage.

**Comment by smallq-git** [comment]
@epicmonkey When I was writing this bug, I logged out, re-opened browser and logged back in - invalid email was displayed, clearly saved.

Right now I cannot reproduce this: email with less than 2 symbols after . is not saved. The only thing that's missing are error messages.
