### ISSUE TITLE
When Posting both to a Group Feed and a User Feed - not visible name Group feed in topic of post

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#214]
Expected: In post topic visible name all groups, where user create post, separated by commas, include name of user feed
![groups 2015-04-20 16-04-30](https://cloud.githubusercontent.com/assets/11980339/7230526/6e5f949e-e777-11e4-9136-03ca2c25448b.jpg)

Actual: Right now visible only name user feed

**Comment by r8** [comment]
@epicmonkey I'll take it

**Comment by epicmonkey** [comment]
Assigned.

**Comment by epicmonkey** [comment]
JFTR, draft version has been promoted in https://github.com/pepyatka/pepyatka-html/commit/3a1371a168984e431adb0ad8be89c37fa21285fa

**Comment by epicmonkey** [comment]
Frontend is in https://github.com/pepyatka/pepyatka-html/pull/390. Backend is in https://github.com/pepyatka/pepyatka-server/pull/213

**Comment by epicmonkey** [comment]
Closing per merged PR.
