### ISSUE TITLE
User stays on sign in page after second login attempt

### ISSUE THREAD

**Issue by ptzn** [pepyatka/pepyatka-html#218]
1. Go to Sign In page https://micropeppa.freefeed.net/#/session/signin
2. Enter invalid login/password
3. Press "sign in" -> see an error
4. Enter valid login/password and press "sign in" again

Expected: user should be redirected to the personal/home page
Actual: user logged in (right sidebar is updated) but stays on the Sign In page

![screenshot 2015-04-18 14 03 35](https://cloud.githubusercontent.com/assets/12827/7234778/381908f0-e792-11e4-9905-18293708231c.png)

**Comment by epicmonkey** [comment]
I was not able to re-create that defect. Summon @smallq-git.

**Comment by ptzn** [comment]
Looks like it fixed now.
