### ISSUE TITLE
Right sidebar always visible

### ISSUE THREAD

**Issue by ptzn** [pepyatka/pepyatka-html#219]
1. Make sure you not logged in or open browser incognito window and go to the https://micropeppa.freefeed.net
2. Sidebar is visible with all "personal" links like "My Discussions", "Direct Messages", etc

Expected: sidebar should not be visible at all or shouldn't contain account-related links.

![screenshot 2015-04-20 19 52 00](https://cloud.githubusercontent.com/assets/12827/7235330/46feafec-e796-11e4-962a-5a1ece9546f6.png)

**Comment by epicmonkey** [comment]
Dup of https://github.com/pepyatka/pepyatka-html/issues/99
