### ISSUE TITLE
Limit usernames to latin characters and acceptable symbols

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#222]
Right now we're not validating usernames at all. I was able to create user with username "[&*\". Naturally, this user is having troubles viewing their feed :)

We need to limit variety of special symbols that could be used in account registration. Acceptable symbols are expected to be underscore (_) and hyphen (-). 
Expected error message when other symbols are submitted: "Username can consist only of latin characters, hyphen (-) and underscore (_)".

**Comment by smallq-git** [comment]
Proofpic:

![image](https://cloud.githubusercontent.com/assets/7983303/7240369/1ea970f4-e7b9-11e4-9f12-a99f7a395cff.png)

**Comment by epicmonkey** [comment]
I'd say instead of white listing we may need black-listing, e.g. old Pepyatka has user https://try.pepyatka.com/users/💊 and this is totally fine.

**Comment by smallq-git** [comment]
lol username "pill".
Blacklisting will work just as well, as long as we remember all the possible issues that could happen with different special symbols. Remember little Bobby Tables.

**Comment by epicmonkey** [comment]
Per discussion -- we should not accept usernames that contain "/". Any other limitations/improvements we will create a new story.

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-server/commit/ec5c58a

**Comment by smallq-git** [comment]
Please disallow backslash too:

![Uploading image.png . . .]()

**Comment by epicmonkey** [comment]
@smallq-git Does it cause any problems with a platform (e.g. user cannot open Comments page or it is not possible to subscribe to that user)?

**Comment by smallq-git** [comment]
@epicmonkey Can't view user's feed, hence can't subscribe.
User themselves can log in, post, comment, like, subscribe.
It's also possible to view individual post pages for the user - in this case \ is replaced with /.

**Comment by epicmonkey** [comment]
That's interesting, thanks. Browsers work with backslash differently, e.g. Firefox doesn't replace backslash to slash (only encodes it to %5c, which is okay), however Safari magically does this.

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-server/commit/91b0d7d7d99f7bab754b8bb122c13afa6c28645f. Does not allow to create a user with a backslash in her username

**Comment by smallq-git** [comment]
Slashes are disallowed.
Users successfully created with special characters: https://micropeppa.freefeed.net/test:test/subscriptions
For ? and % a new issue had been created: https://github.com/pepyatka/pepyatka-html/issues/302
