### ISSUE TITLE
Display breadcrumbs or user profile header on Subscriptions/Subscribers pages

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#223]
Right now there is no way to determine who's Subscriptions/Subscribers page we're viewing, our own or someone else's. It would be nice to have a breadcrumb there or display profile information (like it is for comments/likes).

I was not able to find a screenshot of what it looked like on Frf but I suspect there was a breadcrumb similar to what was displayed for Comments/Likes:
![image](https://cloud.githubusercontent.com/assets/7983303/7240583/d5d90c2a-e7ba-11e4-93f1-c7e6946ca3e3.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/7983303/7240679/8fb41450-e7bb-11e4-972d-311cb418487b.png)

**Comment by epicmonkey** [comment]
We need breadcrumbs for other pages as well, the screenshot you've added is a good example (breadcrumbs on comments page).

**Comment by epicmonkey** [comment]
Reopening, needs more work.
