### ISSUE TITLE
Doubling posts after clicking "Post"

### ISSUE THREAD

**Issue by brain-1** [pepyatka/pepyatka-html#225]
After clicking on a "Post" -  a new entry appears twice
![pepyatka 2015-04-21 19-38-29](https://cloud.githubusercontent.com/assets/11980339/7257390/07df41f0-e85e-11e4-9f8b-49be3e038cb5.jpg)
After refreshing the page - the number of posts displayed correctly

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-server/issues/164

**Comment by kappa** [comment]
May be fixed in https://github.com/pepyatka/pepyatka-html/pull/205

**Comment by epicmonkey** [comment]
@brain-1 can you please verify? I've merged #205 into development branch.

**Comment by brain-1** [comment]
Hurray! Perfecto! (=
