### ISSUE TITLE
Real-time update of times labels

### ISSUE THREAD

**Issue by innin** [pepyatka/pepyatka-html#226]
Post time label can be updated in real-time, e.g. after post it will be something like "just now" then "minute ago", "about hour ago" etc. Now it is static until view changes.

![image](https://cloud.githubusercontent.com/assets/198656/7263539/0357db94-e848-11e4-9c0b-8e4a1a8ca3a0.png)

There is good enough jQuery plug-in for this (supports microformats and localization):
http://timeago.yarp.com/

**Comment by epicmonkey** [comment]
Right now we use momentjs. I wonder if someone has compared those libraries.

**Comment by epicmonkey** [comment]
Okay. Now it's done.
