### ISSUE TITLE
If feed is accessed from scrolled-down page, it will appear scrolled-down as well

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#229]
1. Log in.
2. Go to home or individual feed with several posts in it (e.g. https://micropeppa.freefeed.net/#/cangaroo3).
3. Scroll down.
4. Click any feed name (except the one you're browsing).

Expected: new feed is opened at the top.
Actual: new feed is opened scrolled down to exactly the same place.

Step 3:
![image](https://cloud.githubusercontent.com/assets/7983303/7285734/7262f76e-e94f-11e4-9f22-031768016bed.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/7983303/7285746/84a2dfa2-e94f-11e4-9d02-c8629b5c2847.png)

**Comment by epicmonkey** [comment]
Kind of dup of https://github.com/pepyatka/pepyatka-html/issues/143

**Comment by epicmonkey** [comment]
Resolved per https://github.com/pepyatka/pepyatka-html/pull/374
