### ISSUE TITLE
UI: Comment cloud is misaligned during comment creation

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#230]
When Post Comment field is open, comment cloud is displayed at the top of it.

**Expected:**
![image](https://cloud.githubusercontent.com/assets/7983303/7285782/e811e74a-e94f-11e4-8ea4-f441bfe62eab.png)

**Actual:**
![image](https://cloud.githubusercontent.com/assets/7983303/7285764/bbdba972-e94f-11e4-9ba6-a53efdbca12c.png)

**Comment by epicmonkey** [comment]
Cannot reproduce in Chrome/Firefox anymore.

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/7871331/dd02826a-0597-11e5-8b67-4a10c07f4693.png)
