### ISSUE TITLE
Page is not reloaded when link to it is clicked while on the page

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#233]
1. Log in.
2. Go to any page (e.g. Home).
3. Click link to the page while on the page (e.g. click logo or Home link in the sidebar while on Home page).

Expected: page is reloaded.
Actual: nothing happens.

**Comment by epicmonkey** [comment]
I'm not sure I'm following the issue, can you please explain why is it a defect?

**Comment by epicmonkey** [comment]
I mean this could be UX issue (i.e. no visual effects when user clicks on logo/home), however we already have two stories: 1) to display ajax-spinner on all requests to server 2) scroll browser to the top when she clicks on some links

**Comment by smallq-git** [comment]
@epicmonkey 
In this case I would expect a forced reload, like F5. Instead, the link I'd just clicked is underlined even when I move cursor away and nothing happens.

Use cases:
* Keeping Comments box open for a while, or viewing video. There are no updates happening while you do it. Instead all items get queued and you need to either click "X posts queued" link or logo.
* Viewing feed with real-time updates paused. How do you refresh? (hint: I'd click the logo)
* Being unsure if the page had loaded completely. In this case I'd definitely click the link again.

**Comment by smallq-git** [comment]
Also: https://freefeed.net/artreal/65fe59cd-c3fe-4a24-a6a0-6a072e56c2a9?offset=0

**Comment by indeyets** [comment]
related: https://stackoverflow.com/questions/21481255/how-in-ember-js-reload-current-route

**Comment by smallq-git** [comment]
Effect is somewhat delayed but it works.

**Comment by smallq-git** [comment]
Verified and closed for Homefeed.
For other links new issue is created: https://github.com/pepyatka/pepyatka-html/issues/577
