### ISSUE TITLE
Cannot attach files from individual feed

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#234]
1. Log in.
2. Go to your feed.
3. Attach files to a post.
4. Post the post.

**Expected:** files are successfully attached and displayed in the post.
![image](https://cloud.githubusercontent.com/assets/7983303/7286640/226fcb18-e956-11e4-9aca-9fff33c62381.png)

**Actual:** Post is posted without files.
![image](https://cloud.githubusercontent.com/assets/7983303/7286646/2a997ef6-e956-11e4-9c34-a0c49b9ec94e.png)

**NOTE:** When posting from home, picture preview is present, unlike when posting from individual.
![image](https://cloud.githubusercontent.com/assets/7983303/7286639/20996614-e956-11e4-923f-33f84ceeb2ed.png) ![image](https://cloud.githubusercontent.com/assets/7983303/7286643/272a088a-e956-11e4-96d9-f77522ff58dd.png)

**Comment by epicmonkey** [comment]
Merged changes that should resolve this.

**Comment by smallq-git** [comment]
Even more broken with "v=7366c70f8d4a9db448347bc8ff9da40c4b26eea7": now cannot attach files from Home and Own feed alike.

Note: selected file is not displayed next to the Choose File button.

**Comment by clbn** [comment]
@smallq-git
What is "v=7366c70f8d4a9db448347bc8ff9da40c4b26eea7"? Could you please elaborate on repro steps?

**Comment by epicmonkey** [comment]
@smallq-git @clbn I'm sorry about this. It was a regression caused by https://github.com/pepyatka/pepyatka-html/commit/657275201a37092fe37933949cc6028cf38269c0

@smallq-git Can you take a look in a couple of minutes once deployment is done?

**Comment by smallq-git** [comment]
Verified:
![image](https://cloud.githubusercontent.com/assets/7983303/7303638/c0c93c5a-e9fa-11e4-8c61-03ec9c0d2d78.png)
