### ISSUE TITLE
"Home" is always displayed below logo

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#238]
The word "Home" is supposed to indicate the page the user is viewing. But right now it's displayed on all pages. Example:

![image](https://cloud.githubusercontent.com/assets/7983303/7287154/c20ffb30-e95a-11e4-843a-824374c54ecc.png)

**Comment by smallq-git** [comment]
Breadcrumbs issue: https://github.com/pepyatka/pepyatka-html/issues/223

**Comment by berkus** [comment]
Fixed with as much types of pages we have now and not all looks too good.
