### ISSUE TITLE
Display "Subscriptions" or "Friends" instead of "Users" on Subscriptions page

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#239]
Right now we display the word "Users" when viewing Subscriptions page for a user.
Instead we should say "Subscriptions" or "Friends".

From Frf:
![image](https://cloud.githubusercontent.com/assets/7983303/7287290/e153e8e8-e95b-11e4-97dc-92644abdf3d2.png)

Current view:
![image](https://cloud.githubusercontent.com/assets/7983303/7287301/f0f495cc-e95b-11e4-8d1a-7d70a1695d18.png)

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-html/issues/97

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-html/commit/d488fed7d3c663dd933c393e64593bf2ad4fa077

**Comment by smallq-git** [comment]
now displayed as Friends:
![image](https://cloud.githubusercontent.com/assets/7983303/7380564/457323f4-ee05-11e4-82a6-d7a38a4bc253.png)
