### ISSUE TITLE
Show 3 latest likes and fold others to "X other people" link

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#24]
Show 3 latest likes and fold others to "X other people" link. If a user clicks on that link the application will expand it and show other users who likes that post.

**Comment by berkus** [comment]
Схвачусь пожалуй за это.

**Comment by berkus** [comment]
Additionally, put current user's like to be the first in list.

**Comment by epicmonkey** [comment]
I'm going to reopen this to migrate that solution from master branch to development.

**Comment by smallq-git** [comment]
Collapsed now:
![image](https://cloud.githubusercontent.com/assets/7983303/7332591/f716e0f0-eb4e-11e4-8705-f6d2e7daf00e.png)
