### ISSUE TITLE
When user is not subscribed to anyone but has enough posts, Older/Newer are not displayed on top of 2+ pages

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#240]
If a user had not subscribed to anyone but has made a sufficient number of posts, when they go to the 2+ page, Older/Newer links are not displayed on top of the page for 2+ pages.

Pre-Condition: user with many posts but not subscribed to anyone (shakespeare / shakespeare).
1. Log in with user from pre-condition.
2. Scroll to the bottom of Home.
3. Click Older link.
(scroll up)

Expected: Older/Newer links are displayed at the top of the page.
![image](https://cloud.githubusercontent.com/assets/7983303/7287728/a9adc710-e960-11e4-9dd6-729bd52f271e.png)

Actual: Older/Newer links are NOT displayed at the top of the page.
![image](https://cloud.githubusercontent.com/assets/7983303/7287732/b8a35460-e960-11e4-8a0f-fda7cc745963.png)

**Comment by epicmonkey** [comment]
@smallq-git Could you help me reproducing this one against the latest version please?

**Comment by smallq-git** [comment]
No longer happens - verified on shakespeare
