### ISSUE TITLE
Password is optional on Sign Up form

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#241]
1. Open Sign Up page https://micropeppa.freefeed.net/#/users/signup
2. Enter username.
3. Click "Sign Up" button.

Expected: error is displayed "Please enter your password".
Actual: user is logged in.

NOTE: this is regression to https://github.com/pepyatka/pepyatka-html/issues/176

**Comment by epicmonkey** [comment]
I need help reproducing this one. Cannot re-create on micropeppa and my local environment.

**Comment by smallq-git** [comment]
@epicmonkey Not sure how I can help. It's reproduced for me in Chrome (Incognito and normal) and in IE11 5 times out of 5.

**Comment by epicmonkey** [comment]
That makes sense! It IS reproducible in Chrome, however it is NOT reproducible in Safari. Gosh!

**Comment by epicmonkey** [comment]
Well... at least I saw it one time. Cannot do it anymore. Anyway, thanks. I confirmed it's somehow re-creatable.

**Comment by epicmonkey** [comment]
Got it! You shouldn't focus on password field, i.e.:
- click on Username
- fill in username
- mouse click on Sign up.

**Comment by epicmonkey** [comment]
Fixes in https://github.com/pepyatka/pepyatka-server/commit/3ea9a6eba8080bd405fdb6d7bc129dcaaceb4175. Now it says "Error: Password cannot be blank"
