### ISSUE TITLE
Extra symbol is displayed in breadcrumbs on user's Comments page

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#243]
1. Open user profile.
2. Go to Comments page (https://micropeppa.freefeed.net/#/testo/comments).

Expected: Breadcrumb is displayed correctly.
Actual: "x" symbol is displayed on the line right below breadcrumb.
![image](https://cloud.githubusercontent.com/assets/7983303/7302226/8d5cafaa-e9f0-11e4-90ce-bca3977a0917.png)

**Comment by epicmonkey** [comment]
I love my Emacs!
