### ISSUE TITLE
Internal pages are available to guests

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#245]
If guest opens a direct link to internal pages, we allow them to use them. Instead, we should display a "please sign in" message.

1. Make sure you're not logged in.
2. Follow direct links to pages requiring log in, for example: 
https://micropeppa.freefeed.net/#/groups/new

Expected: Sign In form with message "Please sign in to gain access to this functionality" (or simply Sign In form).
Actual: Page is available and usable.
![image](https://cloud.githubusercontent.com/assets/7983303/7302878/299b594e-e9f5-11e4-81ed-e166ba4c5209.png)

**Comment by epicmonkey** [comment]
i.e.
- home feed
- user settings
- groups settings
- browser/edit groups
- new group page

**Comment by smallq-git** [comment]
Browse/edit groups and new group page now redirect to sign in (https://github.com/pepyatka/pepyatka-html/issues/457 for no returnURL).
Other pages that have to editable elements have them hidden..
