### ISSUE TITLE
no obvious way to change userpic

### ISSUE THREAD

**Issue by earlyadopter** [pepyatka/pepyatka-html#246]
There appears no obvious way to have your avatar changed.
Tried clicking into the icon on a home page and on settings page. Both clicks bring home page instead of expected (at least on a settings page) "change user icon" functionality.

**Comment by epicmonkey** [comment]
True. Right now this is not possible. We already have a story to support profile pictures https://github.com/pepyatka/pepyatka-html/issues/16 and I'm closing this one.
