### ISSUE TITLE
After the subscription user sees the page without links

### ISSUE THREAD

**Issue by wordenhh** [pepyatka/pepyatka-html#251]

**Comment by wordenhh** [comment]
like that http://prntscr.com/6xn85x

**Comment by ptzn** [comment]
Actually user is redirected to https://micropeppa.freefeed.net/#/about instead of staying on subscription page or redirecting to home page.

**Comment by xekc** [comment]
This issue duplicates https://github.com/pepyatka/pepyatka-html/issues/112 should be merged with it.
