### ISSUE TITLE
Current user's "like" is displayed last 

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#257]
In Frf current user's like was always displayed first:
![image](https://cloud.githubusercontent.com/assets/7983303/7332575/fc4eadd8-eb4d-11e4-99ca-17c019a1dd6e.png)

Right now current user's like is always displayed last: 
![image](https://cloud.githubusercontent.com/assets/7983303/7332576/150760ae-eb4e-11e4-9bc1-08bc3d4c157d.png)

**Comment by bleysamberite** [comment]
As of currently on freefeed, my own likes are listed together with the rest in their proper chronological position (not necessarily the last)

**Comment by epicmonkey** [comment]
This is improved now (not fixed though), i.e. server returns current user always in the head, however real-time likes could be in the middle

**Comment by epicmonkey** [comment]
I'm going to reopen this issue. After several real-time events currentUser might become 2nd or 3rd.

**Comment by epicmonkey** [comment]
Closing per merged #413 issue.
