### ISSUE TITLE
[Re-open] Hide post box when viewing other user's feed

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#259]
In Frf post box was hidden when viewing other user's feed:
![image](https://cloud.githubusercontent.com/assets/7983303/7332616/474f2f72-eb50-11e4-8b7e-80766bcfe619.png)

We're displaying the post box right now which leads to confusion (you can create a post but it's not posted when you submit the form):
![image](https://cloud.githubusercontent.com/assets/7983303/7332624/7ca434d8-eb50-11e4-9172-f0e033376cae.png)

**Comment by epicmonkey** [comment]
Could be regression after https://github.com/pepyatka/pepyatka-html/issues/83

**Comment by smallq-git** [comment]
Verified on user's feed and on group I'm not subscribed to feed. Hope there aren't other cases I've missed.

![image](https://cloud.githubusercontent.com/assets/7983303/7339306/f57ff6c6-ec72-11e4-9724-e7fbd52ea6a7.png)

![image](https://cloud.githubusercontent.com/assets/7983303/7339310/028d909e-ec73-11e4-8d27-45ee0e75bfd8.png)

**Comment by smallq-git** [comment]
It's back:
![image](https://cloud.githubusercontent.com/assets/7983303/8021154/feb626d0-0c9c-11e5-8354-3f79937d1a02.png)

**Comment by smallq-git** [comment]
Fixed again.
