### ISSUE TITLE
Show progress spinner on all ajax requests

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#26]
We should show gif progress spinner on all ajax requests so a user knows there is a pending action or something. We could catch all ajax requests by using ```$.ajaxSetup()``` method that sets global AJAX properties that will apply for the entire page.

```
$.ajaxSetup({
  beforeSend: function() {
    // show progress spinner
  },
  complete: function() {
    // hide progress spinner
  }
});
```

Ember-friendly way TBD.

**Comment by iAdramelk** [comment]
It will be a good idea not only show spinner, but also to disable input fields and submit buttons on such requests to prevent second submit or content change after sending request.

**Comment by epicmonkey** [comment]
we have another more detailed story instead of this.
