### ISSUE TITLE
UI: On individual post page comment box is too close to likes and previous comments

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#261]
1. Log in.
2. Open individual post.
3. Observe comment box.

Expected: Comment box is the same distance from likes and comments as comments from each other.
Actual: Comment box appears stuck to the previous comment or likes.
![image](https://cloud.githubusercontent.com/assets/7983303/7332675/e7306666-eb53-11e4-9e4d-56bc827f0aed.png)

**Comment by smallq-git** [comment]
Note that this bug probably affects comment box everywhere but it's not as visible due to comment cloud misalignment (https://github.com/pepyatka/pepyatka-html/issues/230). Since on individual post page the icon is not present (https://github.com/pepyatka/pepyatka-html/issues/260) this issue becomes obvious.

**Comment by smallq-git** [comment]
Please disregard previous comment: this is not reproduced on feed pages:
![image](https://cloud.githubusercontent.com/assets/7983303/7396510/5774f938-eeaa-11e4-9e75-df4c124cffbb.png)

**Comment by epicmonkey** [comment]
Seems already resolved.

**Comment by smallq-git** [comment]
Guess I was right, it was related to comment cloud icon. Fixed now:
![image](https://cloud.githubusercontent.com/assets/7983303/7871310/ca22be26-0597-11e5-930f-ccc30f421cef.png)
