### ISSUE TITLE
If list of likers doesn't fit on one line, "liked this" is displayed on a separate line.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#268]
![image](https://cloud.githubusercontent.com/assets/7983303/7339450/175aeeae-ec78-11e4-9920-242d0028b2c3.png)

**Comment by smallq-git** [comment]
Does not occur anymore:
![image](https://cloud.githubusercontent.com/assets/7983303/7545171/37fc31d2-f5dc-11e4-81f6-10e13e430df4.png)

**Comment by clbn** [comment]
@smallq-git Description says "doesn't fit on one line". On your screenshot it's collapsed.

**Comment by smallq-git** [comment]
Correct verification screenshot:
![image](https://cloud.githubusercontent.com/assets/7983303/7545913/b2a3637e-f5e1-11e4-852c-5e0a62dc0d24.png)
