### ISSUE TITLE
When you try to create post with picture, but without text, post will not be created, but picture field will be claened up

### ISSUE THREAD

**Issue by iAdramelk** [pepyatka/pepyatka-html#275]
How to reproduce:

1. Leave post field blank.
2. Click browse under the post form.
3. Chose image.
4. Click post.

Actual: Post will not be created, but image field will be cleaned up.

Expected: If post was not added, picture filed must stay filled.

**Comment by smallq-git** [comment]
No longer happens because post submission is blocked until there's some text in the field.
