### ISSUE TITLE
Creating group with Username same as reserved words (groups, settings, etc) shouldn’t be allowed

### ISSUE THREAD

**Issue by MrGluek** [pepyatka/pepyatka-html#283]
Right now, when creating new group I may use as username some words which are reserved to technical urls:
* settings
* groups
* filter

After successfully creating I can only open my group from sidebar menu, not via direct URL (because it’s same as some technical URL), example:

https://micropeppa.freefeed.net/#/groups

(can’t open my «groups» group with this URL - it’s reserved to «Browse/edit groups»)

but I can see my «groups» group members with URL:

https://micropeppa.freefeed.net/#/groups/subscribers

but with URL:
https://micropeppa.freefeed.net/#/settings/comments
I can see very strange part of Settings page (only change some «Screen name»).

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/660900b

Here' a current list of reserved usernames:
```
['anonymous',
 'public',
 'about',
 'signin',
 'logout',
 'signup',
 'filter',
 'settings',
 'account',
 'groups',
 '404']
```

**Comment by smallq-git** [comment]
should also be reserved:
friends
list
search
summary
share

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/03a0d733574fb092759876a4da5b632029eb852e

Here's a current blocklist:
```
['anonymous',
            'public',
            'about',
            'signin',
            'logout',
            'signup',
            'filter',
            'settings',
            'account',
            'groups',
            'friends',
            'list',
            'search',
            'summary',
            'share',
            '404']
```
