### ISSUE TITLE
Breadcrumbs on likes timeline page: link is labeled as "Comments" instead of "Likes

### ISSUE THREAD

**Issue by innin** [pepyatka/pepyatka-html#285]
![image](https://cloud.githubusercontent.com/assets/198656/7357675/fb9d0c00-ecf5-11e4-97f2-56565357f0cb.png)

**Comment by smallq-git** [comment]
Looks ok now
![image](https://cloud.githubusercontent.com/assets/7983303/7373561/e70f39f8-edd5-11e4-8fa6-c1f24ea85db4.png)

**Comment by MrGluek** [comment]
Wow I’m famous now! :open_mouth:
