### ISSUE TITLE
Some users cannot create a group

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#292]
1. Log in.
2. Go to Create new group page.
3. Enter "tech" username for the group (https://github.com/pepyatka/pepyatka-html/issues/283).
4. Click Create feed.

Expected: Error is displayed: "Sorry, this username is not allowed".
Actual: Nothing happens. There are error 500 and SyntaxError in console.

**Comment by smallq-git** [comment]
This is reproducible with the following users:
* testuser8 and testuser7 which both have groups with invalid symbols in usernames. 
* testuser9 
* testo (pass Testo) 
* nonumbers (attempted to create a group with hyphen in the name)
* moreau (freshly created, no invalid group names used - I don't know what's wrong with it)

**Comment by id** [comment]
Errors from server:

pepyatka-35 (out): info: User has disconnected from 37c63bf7-93d9-4557-ad89-2506b7b69829 timeline
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err): TypeError: Cannot read property 'trim' of null
pepyatka-35 (err):     at Object.defineProperty.set (/opt/pepyatka/pepyatka-server/app/models/group.js:49:36)
pepyatka-35 (err):     at new Group (/opt/pepyatka/pepyatka-server/app/models/group.js:22:21)
pepyatka-35 (err):     at GroupsController.create (/opt/pepyatka/pepyatka-server/app/controllers/api/v1/GroupsController.js:17:20)
pepyatka-35 (err):     at Layer.handle [as handle_request] (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/layer.js:82:5)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:110:13)
pepyatka-35 (err):     at Route.dispatch (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:91:3)
pepyatka-35 (err):     at Layer.handle [as handle_request] (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/layer.js:82:5)
pepyatka-35 (err):     at /opt/pepyatka/pepyatka-server/node_modules/express/lib/router/index.js:267:22
pepyatka-35 (err):     at Function.proto.process_params (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/index.js:321:12)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/index.js:261:10)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:100:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)
pepyatka-35 (err):     at next (/opt/pepyatka/pepyatka-server/node_modules/express/lib/router/route.js:104:14)

**Comment by id** [comment]
[28/Apr/2015:18:11:13 +0000] "POST /v1/groups HTTP/1.1" 500 22 "https://micropeppa.freefeed.net/groups/new" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36" "-"

**Comment by smallq-git** [comment]
user viking/viking was able to create a group right after it was created but can't anymore :(

**Comment by epicmonkey** [comment]
I was not able to reproduce this on my local environment and I cannot confirm that my latest fix resolved it completely https://github.com/pepyatka/pepyatka-server/commit/6fa52bba217571f4ff6e9c3ff81e144a505c2907. So I'm asking you if you can please check that defect one more time once micropeppa is updated?

**Comment by smallq-git** [comment]
Was not fixed after your fix but now it's not reproduced. I'm blaming accounts with special characters in usernames :-E
