### ISSUE TITLE
[Invalid] Implement Reset password

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#293]
Specs:
https://docs.google.com/document/d/12juTn1Szm-TRf-sYDzVXD_soJ4fgceH70bxGV7q6of4/edit

**Comment by epicmonkey** [comment]
It's there. If you enter your username/password and application doesn't like it, then it'll show you a link "Forgot your password?". Not user-friendly though :-)

**Comment by smallq-git** [comment]
@epicmonkey This is one of the cases where we need to hide functionality because it has not been completed yet: if user uses Reset Password page, no email is sent to them.

Please let me know if this had been implemented and does not work, I will create a bug.

**Comment by epicmonkey** [comment]
This is intended to work. Let's file a bug. (Could be smtp settings)

**Comment by epicmonkey** [comment]
Closing per new story: https://github.com/pepyatka/pepyatka-html/issues/297

**Comment by id** [comment]
pepyatka-5 (err): Unhandled rejection Error: ENOENT, open './app/scripts/views/mailer/resetPassword.ejs'
pepyatka-5 (err):     at Error (native)
pepyatka-5 (err): From previous event:
pepyatka-5 (err):     at Function.Mailer.sendMail (/opt/pepyatka/pepyatka-server/lib/mailer.js:20:8)
pepyatka-5 (err):     at Function.UserMailer.resetPassword (/opt/pepyatka/pepyatka-server/app/mailers/UserMailer.js:12:12)
pepyatka-5 (err):     at Object.<anonymous> (/opt/pepyatka/pepyatka-server/app/controllers/api/v1/PasswordsController.js:24:20)
pepyatka-5 (err):     at processImmediate [as _immediateCallback] (timers.js:358:17)

**Comment by epicmonkey** [comment]
Something is not clicked well, e.g. in the development environment with stdout as a transport I can clearly see rendered resetPassword template.
