### ISSUE TITLE
UI: Better styling for Post box and To: field

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#296]
In Frf:
![image](https://cloud.githubusercontent.com/assets/7983303/7372468/88ec636a-edcf-11e4-85fb-4660c28f43dc.png)

Our version:
![image](https://cloud.githubusercontent.com/assets/7983303/7372552/08a455cc-edd0-11e4-9d8e-5759459ce873.png)

**Comment by smallq-git** [comment]
Now it looks like a blank space in Directs:
![image](https://cloud.githubusercontent.com/assets/7983303/8532465/eaa7935c-2436-11e5-9e34-61b3b42a5389.png)

I know where to click, and you probably do too, but do users know?

**Comment by epicmonkey** [comment]
Moving to 0.3.0

**Comment by smallq-git** [comment]
Fixed (I guess we can ignore square lower corners for now):
![image](https://cloud.githubusercontent.com/assets/7983303/8557648/540cb338-2507-11e5-913d-d8133a5609fe.png)
