### ISSUE TITLE
Reset Password email doesn't reach the mailbox

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#297]
Pre-Condition: account with email specified (yandex/yandex)
1. On Sign In page enter username and incorrect password.
2. Click "Forgot your password" link.
3. Enter email associated with the account.
4. Check your mailbox.

Expected: email with password reset instructions.
Actual: No email.

This is verified with gmail and yandex mailboxes.

**Comment by id** [comment]
Email configuration is not enabled yet on the test instance.
Will do today/tomorrow.

**Comment by epicmonkey** [comment]
I'll keep this open till we update pepyatka-ansible repo (I'm a lazy sod to create a new task there, sorry).

**Comment by berkus** [comment]
Should be using our configured Mandrill creds for sending.
```
service: "mandrill",
auth: { user: "user", pass: "pass" }
```

**Comment by berkus** [comment]
Fixed in ansible/server repos with https://github.com/pepyatka/pepyatka-server/pull/194 and https://github.com/pepyatka/pepyatka-ansible/pull/24
