### ISSUE TITLE
Can subscribe to a group twice right after creation

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#298]
1. Log in.
2. Go to Create group page.
3. Create a group.

Expected: Subscribe link is not displayed if you're already subscribed to the group.
Actual: Subscribe link is displayed for the newly created group and creator can subscribe to their own group (which results in https://github.com/pepyatka/pepyatka-server/issues/173):

![image](https://cloud.githubusercontent.com/assets/7983303/7379773/db81351c-edff-11e4-893a-81d34e808937.png)

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-html/issues/227

**Comment by smallq-git** [comment]
No longer happens.
