### ISSUE TITLE
Custom userpics are not displayed on Subscriptions/Subscribers pages

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#299]
Pre-condition: user has Subscribers and Subscriptions to users with custom userpics (testo/Testo).

1. Log in.
2. Navigate to Subscribers/Subscriptions page.

Expected: if user has a custom userpic, it's displayed on Subscriptions/Subscribers pages
Actual: all users are displayed with default userpics.

In this image cangaroo3 and ivan should have custom userpics:
![image](https://cloud.githubusercontent.com/assets/7983303/7380530/137c0ad2-ee05-11e4-8d4f-843236cd4b5c.png)

**Comment by epicmonkey** [comment]
Good catch! Resolved in https://github.com/pepyatka/pepyatka-server/commit/c5fbd12

**Comment by smallq-git** [comment]
Works now. Will need to check Groups when they have custom userpics
![image](https://cloud.githubusercontent.com/assets/7983303/7389568/e894982a-ee77-11e4-9053-a80f7d13a731.png)
