### ISSUE TITLE
Disallow usernames with the characters ?, %

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#302]
Feeds for these users cannot be viewed (404 is displayed instead).

For user test? user test is displayed instead (note the different userpic).

![image](https://cloud.githubusercontent.com/assets/7983303/7380981/001b00c6-ee08-11e4-9ba7-56911a6b1fe9.png)

**Comment by epicmonkey** [comment]
:monkey: :gun:

**Comment by epicmonkey** [comment]
JFTR: user should not be able to create a group with those symbols.

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/59a27990cdf64c502616a06bd98fdcb6c8ac819e. Blacklists "%" and "?" in username for users and groups
