### ISSUE TITLE
Group date in the right column is not updated when new post is created or commented.

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#303]
Now it shows date when group was created, but needs to be date when either post or comment has been posted last time.

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-server/commit/b2cc4d9a6a29e3f922f5ce113c3cf49ae51c4bd4. Do not change group lastActivity in real-time tho'

**Comment by smallq-git** [comment]
For multi-group posts only the url-owner group is updated:
![image](https://cloud.githubusercontent.com/assets/7983303/8119838/74fe0cd8-10a1-11e5-91ca-f640d0f7d03c.png)

Testuser7 is not subscribed to url-owner group Estonia but subscribed to club soda, yet updated post did not bring club soda into sidebar.

**Comment by smallq-git** [comment]
Works now.
