### ISSUE TITLE
Welcome e-mail - broken link

### ISSUE THREAD

**Issue by bleysamberite** [pepyatka/pepyatka-html#318]
The Login link from freefeed welcome e-mail
Не получается? Первое, что нужно попробовать — зайти на http://about.freefeed.net/login

points to http://freefeed.us10.list-manage.com/track/click?u=5acbb457902f54dbaacdbe84e&id=3d8e1c62a9&e=7b170747c8 and then resolves to http://%20http//about.freefeed.net/login 
that cannot be recognized by the fresh Chrome browser (for windows)

**Comment by berkus** [comment]
Unfortunately can't fix already sent emails :(

**Comment by bleysamberite** [comment]
That's for sure - but at least in the new batch(es), if any - or future mailings on similar topics

**Comment by berkus** [comment]
Thx, we will test better next time!

**Comment by epicmonkey** [comment]
@berkus Can you migrate this issue to freefeed repository if it's still actual?

**Comment by epicmonkey** [comment]
Not actual.
