### ISSUE TITLE
Newest user's post is displayed at the top of offset feed

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#322]
Pre-Condition: user with enough subscriptions to fill 1-2 pages.
1. Scroll down Homefeed and click Older Items.
2. In a new tab create a new post.
3. Submit the post and switch to the tab with the Homefeed.

Expected: Offset feed page is not changed.
Actual: Submitted post is immediately visible at the top of the page.
![image](https://cloud.githubusercontent.com/assets/7983303/7457337/5f6e574a-f294-11e4-82fb-eaea21a2ff61.png)

**Comment by smallq-git** [comment]
Apparently, it could happen for any feed:
![image](https://cloud.githubusercontent.com/assets/7983303/7462449/322106cc-f2ba-11e4-9756-4baf93182980.png)

(but I did not witness this myself)

**Comment by epicmonkey** [comment]
Should be fixed in https://github.com/pepyatka/pepyatka-html/commit/c6b47405d1d4f3e9363fe721aa644c9b83c77cd7 (per #393)
