### ISSUE TITLE
Optimize production mode

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#323]
Currently, code, while works in production mode, still have several suboptimal points:

1. while running, code produces log-messages in browser console
2. the code itself still consists of many independent js-files. Having a single minified and compressed js-file can lead to the speed-boost.

related documentation: http://requirejs.org/docs/optimization.html

**Comment by epicmonkey** [comment]
Can you expand a little on what do you mean by "many independent js-files"? Pepyatka already minifies content and send to a client just three javascript files: require.js, common.js, & main.js.

**Comment by epicmonkey** [comment]
@indeyets Excuse me, did you see my question?

**Comment by indeyets** [comment]
@epicmonkey that was my error, sorry. I saw that there was more than one and considered that as "many"
