### ISSUE TITLE
Current user's username is not displayed as You in the list of likers

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#326]
Expected (in Frf):
![image](https://cloud.githubusercontent.com/assets/7983303/7461884/f1116cc0-f2b5-11e4-9ca7-5780f26efcaf.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/7983303/7461928/3ee57680-f2b6-11e4-8ef8-f02dc51f1715.png)

**Comment by bleysamberite** [comment]
And not only You, but also the first in the list (otherwise it can be easily collapsed into 16 other ppl)

**Comment by smallq-git** [comment]
@bleysamberite That's a separate issue: https://github.com/pepyatka/pepyatka-html/issues/257

**Comment by smallq-git** [comment]
Technically fixed but https://github.com/pepyatka/pepyatka-html/issues/449 exists :(
