### ISSUE TITLE
Comment form is displayed for guest

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#327]
Pre-condition: User is not logged in.
1. Open a feed or a post from a direct URL.

Expected: Comment form is not displayed.
Actual: Comment form is displayed.

**Comment by smallq-git** [comment]
Actual behavior in Frf was (IIRC):
- for logged-in user comment form is immediately displayed on individual post page and on feed/homefeed page displayed after click on Comment link;
- for guest user comment form is always hidden, even on individual post page; click on Comment link brings up login form.

**Comment by epicmonkey** [comment]
I've hidden comment field on individual post page in https://github.com/pepyatka/pepyatka-html/commit/bff1fcd03ad0a77f793703e40383bc3245ebf5e6 revision.
Second point is not implemented yet.

**Comment by epicmonkey** [comment]
@smallq-git Do you think it make sense to separate those items?

**Comment by smallq-git** [comment]
@epicmonkey Yeah, it's basically a new functionality. Created https://github.com/pepyatka/pepyatka-html/issues/419

**Comment by smallq-git** [comment]
Guest user currently doesn't see any links requiring authentication:
![image](https://cloud.githubusercontent.com/assets/7983303/7871555/459c7410-0599-11e5-9ee4-03edfc1ce046.png)
