### ISSUE TITLE
UI: on iPhone Comment box cannot be increased 

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#329]
There is no drag-corner on iPhone for comment box:

![image](https://cloud.githubusercontent.com/assets/7983303/7462395/ce7f3198-f2b9-11e4-980a-63b95cea1f55.png)

**Comment by epicmonkey** [comment]
JFTR: comment field must be auto-expanded to text's height user have entered (for all browsers not just iPhone Safari)

**Comment by epicmonkey** [comment]
auto-expanded has been implemented

**Comment by smallq-git** [comment]
Verified on iphone and android and chrome desktop
