### ISSUE TITLE
Home link for the user keeps offset value

### ISSUE THREAD

**Issue by bleysamberite** [pepyatka/pepyatka-html#340]
Open your feed
Click Older items
(or go directly to https://freefeed.net/?offset=25 for example)
Check the Home link in the top right of your feed (under Friends)

Actual: https://freefeed.net/?offset=25
Expected: https://freefeed.net/

**Comment by smallq-git** [comment]
Possible regression for https://github.com/pepyatka/pepyatka-html/issues/249 and https://github.com/pepyatka/pepyatka-html/issues/144
