### ISSUE TITLE
Fix footer to page's bottom

### ISSUE THREAD

**Issue by teinett** [pepyatka/pepyatka-html#342]
Screenshot: https://yadi.sk/d/mamZkxUcgSBuX
Example: https://freefeed.net/teine/1b36fa7a-d314-4715-8501-52111d7b9f8e

**Comment by epicmonkey** [comment]
Personally, I'm not a big fan of such footers for applications with variable height, however if there are strong UX objections I may agree.

**Comment by teinett** [comment]
Fixed
