### ISSUE TITLE
Can't recover password for existing e-mail

### ISSUE THREAD

**Issue by knikolaj** [pepyatka/pepyatka-html#363]
1) If I try to register I accept the message that e-mail is already taken
2) But if try to recover password (because after registration I didn't accept e-mail), I see the info that e-mail there are no exist in the database.

Nickname: nikolaj
![2015-05-08 15-09-57 freefeed - mozilla firefox](https://cloud.githubusercontent.com/assets/2331310/7536020/569d5e38-f594-11e4-8b80-39ff7546b6e8.png)

**Comment by berkus** [comment]
Known, email is not recorded properly when user is activated from "about".
If you updated your email in profile settings then it would work.

Need to reset password manually in this case.

**Comment by smallq-git** [comment]
html version of https://github.com/pepyatka/pepyatka-server/issues/197

**Comment by epicmonkey** [comment]
@berkus Is it still actual or can be migrated to Freefeed repository?

**Comment by berkus** [comment]
@epicmonkey there's actually a problem in user profile creation on pepyatka - user's email is not properly persisted and until you do profile-update it says email does not exist.

I'll make a separate bug for it however in pepyatka-server.

**Comment by epicmonkey** [comment]
@berkus I'm not sure following you completely. Pepyatka does not have email field on sign up form at all. Please advise.

**Comment by berkus** [comment]
Problem is in pepyatka-server
https://github.com/pepyatka/pepyatka-server/blob/development/app/controllers/api/v1/UsersController.js#L26 and 
https://github.com/pepyatka/pepyatka-server/blob/development/app/models/user.js#L32 this is basically persisted in a weird way - you can see it in client/UI but when you try to perform resetPassword then you get this `Record not found` error.

We call server API endpoint directly with email and hashedPassword set to migrate a user.

Not sure what else's missing on server-side.

**Comment by berkus** [comment]
Might be that this line is missing from user creation, that could explain it.
https://github.com/pepyatka/pepyatka-server/blob/development/app/models/user.js#L292

**Comment by knikolaj** [comment]
Guys, if this situation is unique may be it will be easier to write my e-mail in database directly.
Because now I can't create a new profile and can't login as an existing user. :)

**Comment by epicmonkey** [comment]
@knikolaj Don't worry, PR is already landed to the backend: https://github.com/pepyatka/pepyatka-server/pull/209

**Comment by epicmonkey** [comment]
For any FreeFeed question please send an email to admins.
