### ISSUE TITLE
"... liked this" is duplicated right after user likes a post

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#366]
1. Log in as user Y.
2. Find a post which was already liked by user X.
3. Like the post.

Expected: X and Y liked thisЖ
![image](https://cloud.githubusercontent.com/assets/7983303/7545652/5d1ca214-f5df-11e4-97d3-90bc596fcb38.png)

Actual: X liked this Y liked this:
![image](https://cloud.githubusercontent.com/assets/7983303/7545635/370a37a8-f5df-11e4-8a03-03878755593f.png)

The issue disappears after page is reloaded.

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-html/pull/371

**Comment by epicmonkey** [comment]
Should be better after https://github.com/pepyatka/pepyatka-html/commit/064555b
