### ISSUE TITLE
Rename Post button to Comment when appearing in Comment box

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#368]
In Frf:
![image](https://cloud.githubusercontent.com/assets/7983303/7546231/44b558b0-f5e4-11e4-893b-07c7114bf4c3.png)

In FF:
![image](https://cloud.githubusercontent.com/assets/7983303/7546238/55861bf2-f5e4-11e4-889b-0d154b37ec46.png)

**Comment by epicmonkey** [comment]
@smallq-git Is it for a one page only? AFAIR timeline page showed "Post" and Cancel buttons (the way it's already done in Pepyatka).

**Comment by smallq-git** [comment]
@epicmonkey Can't say. I remember Post and Cancel options as well but so far the only screenshot I was able to find was in One Post spec, and it's indeed for individual post page.
https://docs.google.com/document/d/19YtDcwZELYHrekXxM6T2Dd8pqfhFGrDfEunvio7wqAw/edit#heading=h.8nup6f57uc7a

**Comment by epicmonkey** [comment]
Let's follow the common sense then, i.e. on individual post page Comment field is shown by default, so there is no need to cancel it. However on a timeline page you need to do something to bring it in. Certainly, you may need a way to hide/cancel it. Makes sense?

**Comment by smallq-git** [comment]
@epicmonkey Makes sense, yes. Although I would still have expected button to be called "Comment" when related to comment box.

**Comment by epicmonkey** [comment]
@smallq-git I've changed button to "Comment" on individual post page, tho' left "Post Cancel" buttons in feeds

**Comment by smallq-git** [comment]
![image](https://cloud.githubusercontent.com/assets/7983303/8021139/182cef82-0c9c-11e5-9111-1638cc2ab5ea.png)
