### ISSUE TITLE
Scroll position after click on "Older items"

### ISSUE THREAD

**Issue by dandaka** [pepyatka/pepyatka-html#373]
Now

1. Scroll down the page
2. Click "Older items"
3. Page refreshes
4. Scroll position is really strange... Closer to the bottom. http://take.ms/fd1Qr

Should be

1. Scroll position = top of the page

**Comment by innin** [comment]
duplicates https://github.com/pepyatka/pepyatka-html/issues/143

**Comment by epicmonkey** [comment]
Closing as a dup.
