### ISSUE TITLE
Collapsed URLs in comments should be shorter than originals

### ISSUE THREAD

**Issue by bleysamberite** [pepyatka/pepyatka-html#376]
When adding a URL like https://xkcd.com/599/ at the beginning of a comment, I get it "collapsed" to
https://xkcd.com/599… which is somewhat longer than the original.

**Comment by berkus** [comment]
Can you please reproduce WITHOUT betterfeed?

**Comment by bleysamberite** [comment]
Yep, just did

**Comment by davidmz** [comment]
It is certainly not betterfeed)

**Comment by berkus** [comment]
Ok, mind if i remove all references to betterfeed here? Not to confuse whoever is going to fix this.

**Comment by bleysamberite** [comment]
@berkus whatever helps :)

**Comment by smallq-git** [comment]
![image](https://cloud.githubusercontent.com/assets/7983303/8021039/8198c0de-0c99-11e5-9c93-48234270a459.png)
