### ISSUE TITLE
URL detection algorithm considers a closing square bracket ] to be part of URL

### ISSUE THREAD

**Issue by taivolints** [pepyatka/pepyatka-html#378]
In both posts and comments, when I write a URL in square brackets without a space before the closing bracket:
[SomeURL]
the URL detection algorithm that turns this SomeURL into a link also includes the ending square bracket in the link, so the link will be SomeURL] and will not work.

In FriendFeed the URL detection algorithm did not include the ending square bracket in the link and thus the result was a correctly working link SomeURL within non-link square brackets.

As much as I understand, the only place where square brackets are legal in URI syntax is IPv6 literals. (although, apparently, there do exist cases where some sites produce non-conforming URLs that do contain square brackets)

**Comment by clbn** [comment]
Same bug with parentheses.

**Comment by indeyets** [comment]
seems to be broken. there usecases do not work on [our test-server](https://micropeppa.freefeed.net/testo/28a88790-0f1b-4800-9773-5fdcf8f92863)

```
"https://github.com/pepyatka/pepyatka-html/issues/257"
(https://github.com/pepyatka/pepyatka-html/issues/257)
[https://xkcd.com/599/]
```

**Comment by epicmonkey** [comment]
There are two cases (at least) left:
- google.com -> google.com // without http:// or https://
- http://google.com) -> http://google.com)

**Comment by epicmonkey** [comment]
There is a library that maybe helpful: https://github.com/bryanwoods/autolink-js

**Comment by clbn** [comment]
> google.com -> google.com // without http:// or https://

I'm not sure it's a good idea to link this sort of links. Too many false positives.

**Comment by epicmonkey** [comment]
@clbn Agree. I'm written down examples when regexp parses text incorrectly.

**Comment by indeyets** [comment]
it is reverted to previous status-quo. regexp captures closing brace/bracket/quote

**Comment by epicmonkey** [comment]
@indeyets could you attach your version please? I've tested against the following versions:
![screen shot 2015-06-01 at 21 59 02](https://cloud.githubusercontent.com/assets/117683/7920737/8cf4b6de-08a9-11e5-935d-628dc7a6329a.png)

**Comment by epicmonkey** [comment]
Could it be "http://ya.ru/)" (w/o quotes)?

**Comment by indeyets** [comment]
@epicmonkey live demo: https://micropeppa.freefeed.net/testo/28a88790-0f1b-4800-9773-5fdcf8f92863

**Comment by epicmonkey** [comment]
There are two options how to resolve this (quick-n-ditry ways):
a) remove trailing brackets, parens, dots, etc at the end of the line (black-listing)
b) white-listing urls.
Any other options you see?

**Comment by epicmonkey** [comment]
Per discussion: there is a solid library, we shall consider switching to it: https://github.com/SoapBox/jQuery-linkify

**Comment by epicmonkey** [comment]
@indeyets Let's give it another shot.

**Comment by indeyets** [comment]
:+1:
