### ISSUE TITLE
Change time js library to replace "in a few seconds" and "a few seconds ago" with "just now"

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#379]
This will fix this annoying clock-drift problem.

Absolute timestamp can be shown in mouse-hover.

Related to https://github.com/pepyatka/pepyatka-html/issues/235

**Comment by smallq-git** [comment]
Works.
![image](https://cloud.githubusercontent.com/assets/7983303/7870609/276a3032-0593-11e5-9bc6-e614aee85a30.png)
