### ISSUE TITLE
Cannot browse to Older/Newer items in My Discussions

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#383]
Pre-Condition: user with enough likes and comments to display Older items button on My Discussions (testo/testo).
1. Log in.
2. Go to My Discussions https://micropeppa.freefeed.net/filter/discussions
3. Scroll down and click Older items button.

Expected: URL changes to display offset, previous page is displayed.
Actual: URL changes to display offset, same page is displayed:
![image](https://cloud.githubusercontent.com/assets/7983303/7628391/42233f40-fa2b-11e4-8321-cdaaf83e630d.png)

**Comment by indeyets** [comment]
server issue. closing as dupe
