### ISSUE TITLE
Sometimes own new post is not shown on the homefeed until reload

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#384]
It happened couple of times for me on micropeppa but I've seen a similar issue reported on freefeed: 
1. Create a post.
2. Click Post or press Enter.
3. Wait.

Expected: post is displayed at the top of the homefeed.
Actual: post is not displayed until page is reloaded or homefeed re-opened.

**Comment by epicmonkey** [comment]
I think this was a root cause: https://github.com/pepyatka/pepyatka-html/issues/406#issuecomment-107557394

**Comment by smallq-git** [comment]
Observed it for a while, don't see it happening anymore. Marking verified.
