### ISSUE TITLE
white-screen during initial content rendering

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#386]
We show "loading…" screen, while ember app is not loaded, but…

… there is a pause between "ember app is loaded" and "content is rendered" states, and white screen is shown during this process.

I believe, that this might be the solution: http://guides.emberjs.com/v1.10.0/routing/loading-and-error-substates/

**Comment by indeyets** [comment]
this might be fixed by #374 (needs testing)

**Comment by smallq-git** [comment]
Don't see this happening on desktop (Windows) or mobile (Android).
