### ISSUE TITLE
UI: if list of likers doesn't fit on one line, the list gets displayed one line below like icon

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#391]
Expected: 
![image](https://cloud.githubusercontent.com/assets/7983303/7690326/89117424-fdbb-11e4-8f3c-ae8fccbd2d58.png)

Actual:
![image](https://cloud.githubusercontent.com/assets/7983303/7690332/8f050dbe-fdbb-11e4-8e41-f5c0aecef250.png)

**Comment by epicmonkey** [comment]
JFTR this might become obsolete after https://github.com/pepyatka/pepyatka-html/issues/134

**Comment by smallq-git** [comment]
Issue still present on mobile resolutions with width < 640 px:
![image](https://cloud.githubusercontent.com/assets/7983303/7783837/1f5a16fc-0159-11e5-88bf-22399edd33a4.png)

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/7871253/62504570-0597-11e5-9bf4-3937c2e0bf8c.png)
