### ISSUE TITLE
New friend post is displayed on offset pages and other feeds pages

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#393]
Pre-conditions: Two users logged in in two browsers, where user 1 is subscribed to user 2.
1. With user 1 navigate to offset page for homefeed.
2. With user 2 create a new post.
3. Observe offset homefeed.

Expected: no new posts are displayed on offset pages; new posts are displayed only on homefeed or individual user/group page when posted by this user or into this group feed.
Actual: recent new post is displayed at the top of the feed regardless of which feed/page it is.

NOTE: This is reproduced also for viewing user 1's own feed and other users' individual feeds

**Comment by epicmonkey** [comment]
Connected to https://github.com/pepyatka/pepyatka-html/issues/322
