### ISSUE TITLE
QuotaExceededError in Safari private browsing mode

### ISSUE THREAD

**Issue by haron** [pepyatka/pepyatka-html#394]
Safari 8.0.6, OS X 10.10.3

    QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

![screenshot 2015-05-19 20 24 11](https://cloud.githubusercontent.com/assets/73594/7709347/1529baf8-fe65-11e4-87b2-38941da8c61e.png)

**Comment by epicmonkey** [comment]
@haron I wonder if your Safari uses a custom profile?

**Comment by haron** [comment]
As far as I know, it does not.

**Comment by epicmonkey** [comment]
Is it still happening then or just occasionally?

**Comment by haron** [comment]
The issue still persists, see screenshot attached.

**Comment by berkus** [comment]
Resolved in https://github.com/pepyatka/pepyatka-html/issues/492

**Comment by haron** [comment]
Great, thank you.
