### ISSUE TITLE
Display previous comment when adding a new comment

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#408]
In Frf if user was adding a comment to a post with collapsed comments, the comment above theirs was displayed for some time after comment was posted. We don't have that now which is inconvenient for real-time discussion.

Expected:
1. User reads a post with collapsed comments.
2. User opens comment box without expanding the comments.
3. User responds to the last comment and posts their response.
4. Both last (now next-to-last) comment and user's response are displayed.

Note: I was unable to find comment behavior in specs, so that's based on user's feedback.

IIRC, if I was adding a comment and someone else was posting their comment at the same time, I saw that someone else's comment without comment I was responding to being collapsed. But this is only from my memory.

**Comment by epicmonkey** [comment]
Linking with https://github.com/pepyatka/pepyatka-html/issues/21

**Comment by smallq-git** [comment]
![image](https://cloud.githubusercontent.com/assets/7983303/8021119/d655c7dc-0c9b-11e5-85a6-d0ee5d2083ed.png)

Other people comments also properly appear above my comment box while I'm typing. Unfortunately, they're collapsed to 2 last comments. But this issue will have to be dealt with when we implement update pause.

**Comment by epicmonkey** [comment]
AFAIR that's how it was implemented in FrF.
