### ISSUE TITLE
My earlier liking of a post sometimes not shown until I unfold likes

### ISSUE THREAD

**Issue by taivolints** [pepyatka/pepyatka-html#409]
In many cases (but not always), when I look at some post that I know I have liked earlier and that post has so many likes that the likes get folded, the post looks like I have NOT liked it — there is "Like" link instead of the "Un-like":

![01](https://cloud.githubusercontent.com/assets/3599074/7791781/586bc74a-02af-11e5-8586-b0132777f412.png)

If I then unfold the likes, then it gets fixed automatically: "Like" turns into "Un-like" and my name appears in the list:

![02](https://cloud.githubusercontent.com/assets/3599074/7791782/612586e6-02af-11e5-9db4-de822bada2d3.png)

**Comment by epicmonkey** [comment]
Resolved in the backend.

**Comment by smallq-git** [comment]
Not reproduced anymore.
