### ISSUE TITLE
My like is shown first in the list of likes

### ISSUE THREAD

**Issue by taivolints** [pepyatka/pepyatka-html#410]
When I look at the list of likes of a post that I have liked, then my like is currently shown first in the list regardless of when I liked the post compared to other likers.

In FriendFeed, as much as I remember, the timewise ordering of the likes applied to myself as well, so that if anybody to whom I was subscribed had liked the post later than I, then their names were in front of my name in the list of likes. This allowed me to find out if I had liked the post earlier or later than some particular friend of mine, which was sometimes useful / important knowledge for me. (the likes of those people to whom I was not subscribed were in a separate timewise sorted group after the likes of those people to whom I was subscribed, though, so comparison of my liking time with those was not possible).

**Comment by epicmonkey** [comment]
We need a fact check. @smallq-git could you verify? AFAIR my like is always in the head.

**Comment by taivolints** [comment]
Hm, oops, seems that I remember it incorrectly, indeed. I guess the issue can be closed / removed, then.

Interesting. I guess part of the reason for my confusion is that some of the Like features are not implemented yet as they were in FriendFeed (displaying "You" instead of screenname, and grouping the likes based on my subscriptions), so the list of likes looks somewhat different than it was in FriendFeed — there was never "Taivo Lints" in the beginning of the likes list in FriendFeed when I was signed in, so in FreeFeed it feels wrong to me that there is "Taivo Lints" in the beginning of the likes list. It's just that the actual problem is not the location, but the screenname instead of "You". As of finding out who of my friends had liked a post before or after me, I guess the main helper feature in FriendFeed was that the likes of those people whom I was subscribed to were displayed first in the list of likes, so I could easily notice and remember if those friends of mine who would be likely to like that particular post had already liked it or not at the moment when I liked it.

**Comment by epicmonkey** [comment]
Indeed. Thanks, we are going to improve this eventually.
