### ISSUE TITLE
Click on Add: Photos link should open Choose File dialog directly.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#418]
Right now if user clicks Add: Photos link, they then need to click Choose File button and there is no Cancel button at this point.

In Frf when Photos (or Files) link was clicked, standard Choose File dialog was opened without additional actions from the user. 

For more information see Direct Messages spec, Creating a Direct Message section:
https://docs.google.com/document/d/1rNfM6N-JyZtsWY2UupM3Q9_roVvNrG5oQFIxHbeanpg/edit#heading=h.xhohkn5wkzc0

**Comment by epicmonkey** [comment]
That's helpful!

**Comment by clbn** [comment]
FTR: this one may be related to #130 (which has a confusing title), they might be fixed in one change eventually.
