### ISSUE TITLE
Expanding comments brings post to the top.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#422]
Pre-condition: post with enough comments on home or individual user's feed not in the top position.

1. Log in.
2. Scroll to the post from pre-conditions.
3. Like the post.
4. Click link to expand comments.

Expected: comments are expanded and I'm able to read them right away.
Actual: post jumps up, comments are expanded but to read them I need to scroll to the top and then back down to continue reading my feed.

Workaround is to click "like" AFTER expanding comments or commenting. But it's annoying to keep that in mind.

This doesn't happen other way around: if you comment/expand comments and then like, post remains where it is on the timeline.

**Comment by epicmonkey** [comment]
New comment first and then unfold likes another case. And third one: when user updates her post, it'll be bumped. Fix above resolves those 3 items.
