### ISSUE TITLE
update Bootstrap

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#424]
[Bootstrap 3.3.4](http://blog.getbootstrap.com/2015/03/16/bootstrap-3-3-4-released/) was release some time ago with tons of fixes

**Comment by epicmonkey** [comment]
This requires only js library. We already use 3.3.4 css version.

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-html/commit/67ab1b165e19b1ad68eb574b3a9b5ffb9dd259e0
