### ISSUE TITLE
limit groups in the right panel to X

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#431]
Check the specs, X might be 3.

**Comment by smallq-git** [comment]
I see four groups:
![image](https://cloud.githubusercontent.com/assets/7983303/7995719/7b9cc4d8-0b21-11e5-9b4e-91426d6a0d31.png)

**Comment by epicmonkey** [comment]
Argh! Spec says it must be 4. Description is wrong.
