### ISSUE TITLE
prettify post titles (groups it has been published to)

### ISSUE THREAD

**Issue by epicmonkey** [pepyatka/pepyatka-html#432]
e.g. separate groups with commas

**Comment by epicmonkey** [comment]
Reopening to handle case when user screenName ends with "s", e.g. for user "mars" we'll show "to mars' feed" not "to mars's feed"

**Comment by smallq-git** [comment]
Pretty enough:
![image](https://cloud.githubusercontent.com/assets/7983303/8070325/21468a64-0f09-11e5-9ded-c6787263521d.png)
