### ISSUE TITLE
Can't change group's screen name

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#437]
Error is displayed: undefined is not a function

![image](https://cloud.githubusercontent.com/assets/7983303/7953854/62f5d320-09d2-11e5-8ad9-ab9b0a0e225a.png)

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/7d2c10e94334cbc4ba57ce2e9450cbd7aded4382. Covered with auto-tests.
