### ISSUE TITLE
Post form is displayed for unsubscribed user on group page (for group creator)

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#439]
It's unresponsive, but it shouldn't be there in the first place.

![image](https://cloud.githubusercontent.com/assets/7983303/7953909/2ee61b34-09d3-11e5-956c-ddb09735f54b.png)

**Comment by epicmonkey** [comment]
Closed after #440.

**Comment by smallq-git** [comment]
Now not displayed:
![image](https://cloud.githubusercontent.com/assets/7983303/8071293/51530144-0f11-11e5-919e-b2487784f051.png)
