### ISSUE TITLE
Post form is not displayed on group page for subscriber

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#440]
If subscriber is not group creator, post form is not displayed on group page.

![image](https://cloud.githubusercontent.com/assets/7983303/7954057/95bb9cde-09d4-11e5-8c20-ffefac7b6009.png)

**Comment by epicmonkey** [comment]
That was a really good one. I have not touched this code for a while. Thanks.

**Comment by epicmonkey** [comment]
Connected to #439.

**Comment by smallq-git** [comment]
Now displayed: 
![image](https://cloud.githubusercontent.com/assets/7983303/8071288/3a4231be-0f11-11e5-8bbd-f0ecb515af81.png)
