### ISSUE TITLE
Realtime updates might remove comment-form

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#441]
Sometimes, real-time updates aggressively replace code and form with an unfinished comment is removed.

@xekc might have more details

**Comment by berkus** [comment]
They sure do!

Especially on front-page where frequency of updates is high it's literally snatching the comment form with all contents out of your hands.

**Comment by indeyets** [comment]
I suppose (pure speculation) that existence and contents of form is not reflected in view's state. So, as full-rewrite is happening, engine just doesn't know that it's doing the bad thing

**Comment by epicmonkey** [comment]
Confirm. Steps to reproduce:
- two tabs with home feed are open
- open comment form in the first tab
- in the second tab create a new post

expected result:
- post appears in both first and second tabs
- comment form is open

actual result:
- post is on top in both tabs
- comment form is not visible anymore.

**Comment by epicmonkey** [comment]
Need to review TimelineHomeController#allPosts and TimelineHomeController#posts
