### ISSUE TITLE
List of /groups shows only 6 groups maximum

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#444]
I've created about 15 groups.

The "Browse/edit groups" page shows only 6:

![](https://dl.dropboxusercontent.com/s/s5gjdl96q5gqffn/2015-06-04%20at%2003.01.png)

**Comment by epicmonkey** [comment]
At the very top there is a switcher: all groups | active groups

**Comment by berkus** [comment]
Haaalelujah!

**Comment by berkus** [comment]
Maybe use All groups by default though? Not sure what the activity criteria is, but it only showed the latest groups i created, not the groups that had ANY activity.

**Comment by indeyets** [comment]
Friendfeed, as far as I remember showed "active" on top and "all" below, as far as I remember. there was no need to switch anything

**Comment by epicmonkey** [comment]
@indeyets it was showing active at the top by default and then *posts* from all groups below (I'm not sure there was a pagination on the page though).

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-server/commit/8b59b46

**Comment by smallq-git** [comment]
@epicmonkey What was the fix for this? I see no changes.

**Comment by epicmonkey** [comment]
Group is going to be updated if someone likes a post or leaves a comment. Let me double check though if it's on peppa already.

**Comment by epicmonkey** [comment]
Yes, it's been promoted to freefeed repo, so it should be on peppa.

**Comment by smallq-git** [comment]
So right now "Active groups" means "6 groups that were updated last".
ATM "updated" means "were created or had new comments" but in the future this should mean "were created or had new posts, likes or comments".

**Comment by epicmonkey** [comment]
I guess we should re-open this one as well?

**Comment by smallq-git** [comment]
Looks like it's fixed properly now: I see only groups that had some activity lately.
