### ISSUE TITLE
Subscribers count is wrong for groups

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#451]
Number of subscribers is off for groups. For example, group tree has 5 subscribers on profile page but only two subscribers are listed.
https://micropeppa.freefeed.net/tree

**Comment by epicmonkey** [comment]
This could be a corrupted data, sorry about that. Could you verify with a new group?

**Comment by smallq-git** [comment]
not now, sorry: testo is broken again and I don't have time to work with another user.

**Comment by smallq-git** [comment]
I don't see this happening to groups created less than a week ago, so I'm closing this issue.
