### ISSUE TITLE
An attached image is not shown until page is refreshed

### ISSUE THREAD

**Issue by id** [pepyatka/pepyatka-html#458]
If a user creates a post with an image as attachment, the image is not shown together with the post until page is refreshed.

**Comment by epicmonkey** [comment]
This is a regression.

**Comment by epicmonkey** [comment]
Broken after upgrade to the latest ember in https://github.com/pepyatka/pepyatka-html/commit/0c674acbe7bf9bbea898977bcc13869c61d5e966

**Comment by smallq-git** [comment]
Doesn't seem to happen anymore.
