### ISSUE TITLE
Last update date for groups is incorrect

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#466]
Timestamp in the sidebar should be equal to the last post date. Right now it still equals group creation date:

![image](https://cloud.githubusercontent.com/assets/7983303/8046003/30831034-0e40-11e5-9582-e9543bf2281e.png)

**Comment by smallq-git** [comment]
Looks like https://github.com/pepyatka/pepyatka-html/issues/303 is simply not fixed.

**Comment by epicmonkey** [comment]
I'd say group last activity in the right panel and on groups page (/groups) is updated after F5.

**Comment by epicmonkey** [comment]
Furthermore, it maybe even wrong to update them in real-time (from UX point of view), groups will be dynamically jumping from one to another position.

**Comment by smallq-git** [comment]
no it's not. The screenshot was taken after logout and re-login. You can log in to testo/testo and see for yourself.

**Comment by epicmonkey** [comment]
A bit more details on this issue: new post and new like do not update group last activity date, however new comment does.

**Comment by smallq-git** [comment]
Now I see that it's updated after page reload but don't see changelog attached. Is this an accidental fix?

**Comment by epicmonkey** [comment]
Connected to #303.

**Comment by smallq-git** [comment]
Works now
