### ISSUE TITLE
Unify interface languages

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#482]
Several people requested for interface to be unified to one language.

Suggested translation for Feedback section:
Feedback
About
Ask a question
Report an issue
Get updates
Suggest a feature

**Comment by urbansheep** [comment]
Translation for the donation section:

Coin Jar
Subscribe to Freefeed today! Arrangement is plain and simple — you wire funds to Freefeed, it gets better every week.

Choose your option:

Or try sending a one-time payment first →

**Comment by urbansheep** [comment]
Add-ons:
BetterFeed:
[_] Enable BetterFeed.
BetterFeed is an add-on with a number of options that improve or dramatically alter stock interface of the FreeFeed (usually to the better).

**Comment by berkus** [comment]
Re BetterFeed - see also https://github.com/davidmz/BetterFeed/issues/2

**Comment by berkus** [comment]
Based on latest text from David:

[_] Enable BetterFeed.
BetterFeed is an add-on that improves or dramatically alters stock interface of FreeFeed (details).
**Important:** BetterFeed settings are stored in your local browser. They are not tied to FreeFeed account and are not automatically synced between sessions in different browsers.

[Apply]

**Comment by smallq-git** [comment]
![image](https://cloud.githubusercontent.com/assets/7983303/8262611/2f8aa6ac-16dc-11e5-926d-99a5c3d3d1bf.png)
