### ISSUE TITLE
Subscribe link is available for blocked user

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#486]
1. Log in.
2. Open user profile for a user you're not subscribed to.
3. Click Block User link.

Expected: Subscribe link is not visible for a blocked user.
Actual: Subscribe link is present and active - you can subscribe to a blocked user, which is odd.
![image](https://cloud.githubusercontent.com/assets/7983303/8150466/0c3f6746-12f4-11e5-84bf-ee6d77260ea1.png)

**Comment by epicmonkey** [comment]
Fixed in https://github.com/pepyatka/pepyatka-html/commit/806e89e54be8cf3ba4231f4280c67d1781633722

**Comment by smallq-git** [comment]
Fixed:
![banned](https://cloud.githubusercontent.com/assets/7983303/8291636/70eae1bc-1933-11e5-9a39-387e05364599.jpg)
