### ISSUE TITLE
Block this user blocks groups where blocked user commented or liked posts.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#490]
1. Log in (testuser3/testuser3).
2. Open other user's profile (https://micropeppa.freefeed.net/testuser7/).
3. Click Block this user link.
4. Open group feed of any group this user liked or commented in (https://micropeppa.freefeed.net/estonia).

Expected: group feed is visible sans blocked user's posts, comments and likes.
Actual: group is blocked without option to un-block (Un-block link is present but doesn't work):

![image](https://cloud.githubusercontent.com/assets/7983303/8150536/234b124e-12f6-11e5-9779-356321968366.png)

**Comment by epicmonkey** [comment]
Cannot reproduce after https://github.com/pepyatka/pepyatka-html/commit/4322cbeba124efb014d7621fb794f1666fa6c8e1

**Comment by smallq-git** [comment]
Indeed doesn't happen anymore
