### ISSUE TITLE
Add option to show user names instead of display names

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#498]

**Comment by epicmonkey** [comment]
Let's discuss. I'm not seeing this a part of the client yet.

**Comment by berkus** [comment]
I can add it as freefeed-only feature if necessary. These are just little gimmicks that didn't exist in FrF.

**Comment by epicmonkey** [comment]
The thing is -- more we develop the client, more requests will come from users and there is no silver bullet. I'm not sure what the balance is (other than strictly focusing on FrF features first, certainly). In the perfect world I would rather do this on top an existing client, could be BetterFeed or 3rd party applications (that is another pretty cool topic to research).
