### ISSUE TITLE
[Verified] Ban: banned user should not be able to re-subscribe to banning user

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#505]
If user1 is subscribed to user2, and user2 had blocked user1, user1 should lose the ability to subscribe to the user.

Right now we do not hide Subscribe link for banned user. Clicking it doesn't result in any changes on the page but banning user's posts still appear in the homefeed.

See testo/testo (banning user) and testuser1/testuser1 (banned user).

**Comment by smallq-git** [comment]
I don't remember how that was implemented in Frf but I think there was a warning for banned user on banning user's page.

**Comment by urbansheep** [comment]
To clarify:
In FRF when banned user visited restricted user's profile, she saw a message “This user is private”. Clicking on “Subscribe” button at first led to common “your request was sent” message, but later it got deferred to plain 403 error message.

For our purposes I suppose it's better to show a non-ambiguous message “This user has disallowed your kind at their premises” and disable “Subscribe” button.

Ban is a state that can always be noticed or deduced by side effects and there's little reason to not explain it upfront especially for users who have less experience and were not previously well-trained by the quirks in FRF interface.

**Comment by smallq-git** [comment]
I suspect that in Frf banning user was literally "privated" for the banned user, hence the message. Ban behavior supports this theory too.

**Comment by berkus** [comment]
It is not possible to resubscribe now, although the UI changes only consist of returning an error "This user has prevented you from subscribing to them."

**Comment by berkus** [comment]
Pls open separate issues for remaining visual improvements
- Styling 403 messages in the app better
- Disabling subscribe button?

**Comment by smallq-git** [comment]
Better presentation: https://github.com/pepyatka/pepyatka-html/issues/528
Actually show the error: https://github.com/pepyatka/pepyatka-html/issues/529

For discussion, disabling  Subscribe: https://github.com/pepyatka/pepyatka-html/issues/530

**Comment by smallq-git** [comment]
technically fixed.
