### ISSUE TITLE
[Verified] Comment's textarea should grow following entered text length

### ISSUE THREAD

**Issue by indeyets** [pepyatka/pepyatka-html#508]
Currently, the size of textare for comments is limited to single line and it hurts usability (editing long text is a complex task). Also, it seriously hurts mobile experience.

Textarea size should be dynamic. It should grow (and shrink) following the length of text entered in it.

Similar functionality is available in betterfeed. We can use it as a base, probably: https://github.com/davidmz/BetterFeed/blob/master/src/js/actions/textarea-fix.js

**Comment by urbansheep** [comment]
At the moment even with Betterfeed when I edit older posts Freefeed offers me a single line text-area. Let's make it at least 2,5em tall, please.

**Comment by smallq-git** [comment]
Comment and post textarea now automatically increases as user types. New issue is opened for default comment box size: https://github.com/pepyatka/pepyatka-html/issues/517
