### ISSUE TITLE
[Verified] Posting a picture doesn't show it until refresh.

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#512]
See
https://freefeed.net/bugreport/e71651f2-9eb5-47d9-b642-8f7456d6a1bf?offset=0

**Comment by clbn** [comment]
I saw this once on freefeed.net, but cannot reproduce on micropeppa or on my instance.

**Comment by berkus** [comment]
Looks like it's reliably reproducible for @davidmz

**Comment by clbn** [comment]
Fixed in #548.

**Comment by smallq-git** [comment]
Does not happen anymore
