### ISSUE TITLE
[Verified] Change Post button to Save when editing a post

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#516]
In Frf when post was being edited, Post button was changed to Save:
![image](https://cloud.githubusercontent.com/assets/7983303/8388179/f99af394-1c67-11e5-9e37-d73c76c082ba.png)

In ff right now it's always Post:
![image](https://cloud.githubusercontent.com/assets/7983303/8388185/0664c0f0-1c68-11e5-9390-5b9b632f4380.png)

**Comment by Nek** [comment]
assigning this one to myself

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/8511108/601f7a18-2311-11e5-8aee-8213047ba658.png)
