### ISSUE TITLE
[Verified] Ban: Can see new comments by banned user on group or 3rd user's posts

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#521]
Pre-condition: user1 banned user2.

Steps:
1. Open group's feed as user1
2. Comment on a group post as user2.

Expected: user1 does not see any comments by user2.
Actual: user1 sees comments by user2.

![image](https://cloud.githubusercontent.com/assets/7983303/8394055/c16ee1a0-1d30-11e5-9f1a-07e4950f18c2.png)

Note that older comments are not visible, and comments disappear after page reload.

**Comment by smallq-git** [comment]
still happens in real-time. disappears on reload.

**Comment by clbn** [comment]
Still can reproduce on micropeppa (realtime part only):

Pre-condition:
1. User-A and User-B are both subscribed to Group-C.
2. User-B has banned User-A.

Steps:
1. Open Group-C's feed as User-A in one browser.
2. Open Group-C's feed as User-B in another browser.
3. Post to the group as User-A.

Expected:
User-B does not see any new posts show up in the Group-C.

Actual:
User-B sees new posts from User-A on Group-C's page (as realtime updates). After reload they dissappear.

**Comment by clbn** [comment]
Seems fixed, cannot reproduce on micropeppa (both realtime and after reload):

Pre-condition:
1. User-A, User-B and User-C are subscribed to Group-D.
2. There is a post from User-C in the group.
2. User-B has banned User-A.

Steps:
1. Open Group-D's feed as User-A in one browser.
2. Open Group-D's feed as User-B in another browser.
3. Comment on User-C's post in the group as User-A.

Expected == actual:
User-B does not see any new comments show up in the Group-D as realtime updates, and cannot see them after page reload.

In the opposite direction, it also works as intended: comments by User-B show up in User-A's browser.
