### ISSUE TITLE
[Verified] Ban: Banned user is not automatically unsubscribed from banning user

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#522]
Pre-condition: 
1. user1 is not subscribed to user2 (otherwise they will not be able to ban: https://github.com/pepyatka/pepyatka-html/issues/500)
2. user2 is subscribed to user1.
1. As user1 ban user2.
2. As user2 view user1's profile.

Expected: Limited profile displayed (only userpic and displayname)
Notification: "This user has blocked you on this service"
Subscribe button is not available.

Actual: profile is displayed normally, Unsubscribe button is available.
(subscribe button is available after unsubscription - https://github.com/pepyatka/pepyatka-html/issues/505)

**Comment by berkus** [comment]
Already added this, testing some cases locally.

**Comment by smallq-git** [comment]
Text for this case is not discussed yet. In Frf there was no outright indication that user1 had banned user2 - they simply appeared private.

**Comment by berkus** [comment]
For first release we will simply limit possibility to subscribe.

**Comment by smallq-git** [comment]
Not actually fixed.

**Comment by berkus** [comment]
What exactly is not fixed?

**Comment by smallq-git** [comment]
Now I can't reproduce it anymore. Perhaps it was a ban performed before this fix was introduced.
