### ISSUE TITLE
[Verified] Collapse pictures on individual post page

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#525]
In Frf on individual post page thumbnail behavior was the same as in homefeed: if combined thumbnails width exceeded 450px, they were collapsed under expander arrow.

**Comment by clbn** [comment]
@smallq-git @urbansheep
Still, I vaguely remember that behaviour on individual post page was different from the timeline. And if not all images were visible, maybe there was e.g. 2 rows of images instead of one?

**Comment by urbansheep** [comment]
I might be mistaken, but still my (quite possibly false) memories tell a story of “all comments are expanded, image set is collapsed on a single post page”. And maybe we can support both modes with a switch in a global config so that we don't commit/rollback things in case they don't work out?

**Comment by clbn** [comment]
Well, it's quite simple to implement the same behaviour on the post page (one row is visible) once it's done to the timeline, so we can do it if it's fine by you.

Actually, the two rows case would require a different algorithm to implement. :)

**Comment by urbansheep** [comment]
It's fine with me!

By the way, do we have any file number limit imposed when attaching files to the post?

**Comment by clbn** [comment]
OK, will do.

AFAIK, there is no limit for number of attachments currently.

**Comment by urbansheep** [comment]
I guess we'd better enforce at least some reasonable limit (up to 5 files, up to 20 images), otherwise we might meet with some nasty “boundary testing” similar to what we've seen with unlimited strings length in usernames, when linker used a huge blob of text as a username which made frf unusable for a while.

**Comment by clbn** [comment]
Sure, let's do it.

**Comment by smallq-git** [comment]
Implemented:
![image](https://cloud.githubusercontent.com/assets/7983303/8534263/583d5b0c-2443-11e5-9599-5dc20e4258c1.png)
