### ISSUE TITLE
[Verified] Direct: Non-mutual friends are present in the To: dropdown 

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#535]
Pre-condition: user1 is subscribed to user2 but user2 is not subscribed to user1,
1. Go to Direct Messages.
2. Click postbox - To: - Add/Edit.
3. Type first letters of user2's name.

Expected: user2 is not present in the list because they're not subscribed to user1.
Actual: user2 is present in the list.

**Comment by berkus** [comment]
I think @epicmonkey had a fix for this already.

**Comment by epicmonkey** [comment]
Right, tho' it's not on peppa yet.

**Comment by berkus** [comment]
Is it pushed? I didn't find it yesterday.

**Comment by epicmonkey** [comment]
Np: https://github.com/pepyatka/pepyatka-html/commit/a2f84e0c3340fff7d2ea5b90e887daffeb606813

**Comment by berkus** [comment]
Pepped it. Closing.
