### ISSUE TITLE
[Verified] Direct: Attached pictures are not visible in the message (intermittent)

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#553]
Pre-condition: user1 and user2 are mutual.

When you compose and sent a message with a picture in it, it will intermittently be displayed without picture until page is refreshed or next message is sent.

Note that this is reproduced and not reproduced with exactly the same pictures so I'm not sure what's causing this.

**Comment by berkus** [comment]
Source ticket in https://github.com/pepyatka/pepyatka-html/issues/512

This is the same issue apparently.

**Comment by clbn** [comment]
Fixed in #548.
