### ISSUE TITLE
[Verified] Direct: message timestamp is not refreshed intermittently

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#554]
It's expected that for visible in the feed/DM section messages timestamp will be refreshed as time passes.

Right now for some messages it randomly doesn't happen.
![image](https://cloud.githubusercontent.com/assets/7983303/8534082/e48301b8-2441-11e5-8b42-11d5cac8ec3a.png)

**Comment by Nek** [comment]
There is a better way to deal with setInterval:
http://guides.emberjs.com/v1.10.0/cookbook/working_with_objects/continuous_redrawing_of_views/

**Comment by Nek** [comment]
This is very important:
UNCONSUMED COMPUTED PROPERTIES DO NOT TRIGGER OBSERVERS
http://guides.emberjs.com/v1.10.0/object-model/observers/

That's why there is:
```
init: function() {
      this._super()
      this.get('createdAt')
      this.get('currentTime')
    }
```

Without this part the newly created posts' time won't be updated at all.

**Comment by smallq-git** [comment]
Update is a bit delayed when direct is viewed from homefeed but insignificantly so.
