### ISSUE TITLE
[Verified] Expand/collapse icon is displayed on individual post page even when there's only one picture

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#561]
Single-picture post in the feed:
![image](https://cloud.githubusercontent.com/assets/7983303/8581905/50e1d830-25cc-11e5-9aab-30bced182d34.png)

And on individual page:
![image](https://cloud.githubusercontent.com/assets/7983303/8581903/4c24a8cc-25cc-11e5-8250-0c97ed7d8b25.png)

**Comment by epicmonkey** [comment]
I cannot reproduce this. Could someone please review this?

**Comment by epicmonkey** [comment]
This is a bit tough to reproduce, lowering priority.

**Comment by smallq-git** [comment]
This is no longer happening.
![image](https://cloud.githubusercontent.com/assets/7983303/9185352/cb719d36-3fc3-11e5-85f7-d5bcd812c486.png)
