### ISSUE TITLE
[Verified] Posts older than 2 months display Not Found error 

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#562]
For all posts created before a certain point Not Found error is displayed on individual post URL and console has 403 error:
https://micropeppa.freefeed.net/v1/posts/728e9313-1417-44ee-8812-c8db486d4f93?maxComments=all Failed to load resource: the server responded with a status of 403 (Forbidden)

This happens for posts from May 19th for sure, maybe later. Posts starting from at least May 28 are ok.

Post from May 19th (not ok):
https://micropeppa.freefeed.net/testo/728e9313-1417-44ee-8812-c8db486d4f93

Post from May 28th (ok):
https://micropeppa.freefeed.net/testo/3d1c9a13-1878-43b7-b161-b2b60e3a906a

**Comment by epicmonkey** [comment]
This migration should update post:&lt;postId&gt;:to key based on post:&lt;postId&gt;:timelines if it's empty. https://gist.github.com/epicmonkey/6ae90583c3cba1d2d215

**Comment by epicmonkey** [comment]
summon @berkus @indeyets

**Comment by berkus** [comment]
epicmonkey [7:50 PM] 
^ прежде чем на пеппе запускать, сделайте дамп базы. чтобы можно было больше одного раза прогнать, если потребуется.

**Comment by smallq-git** [comment]
When likes or comments expand is attempted on those posts, eternal loading is displayed. In console:

https://micropeppa.freefeed.net/v1/posts/dbdeb0b7-7b5f-4353-b149-f48f94c8f051?maxComments=2&maxLikes=all Failed to load resource: the server responded with a status of 403 (Forbidden)
config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:35919 Error: Forbidden
    at a.extend.ajaxError (config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:56613)
    at s.error (config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:56613)
    at fire (config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:3186)
    at Object.self.fireWith [as rejectWith](config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:3298)
    at done (config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:8353)
    at XMLHttpRequest.<anonymous> (config.js?v=f26229514e7aa49951d576dd14373ab0d5eea764:8692)

**Comment by berkus** [comment]
RDB dump made, running script.

**Comment by berkus** [comment]
Script executed, posts are now being loaded correctly.

**Comment by berkus** [comment]
Some posts are still not fixed by this.

**Comment by berkus** [comment]
squadette [3:38 PM] 
уважаемые коллеги, https://freefeed.net/yole/comments -> верхний пост Сумина с обращением к Линкеру — click "2 months ago" -> "Not Found".  Если попытаться там открыть комменты, то возникает бесконечный червяк.

squadette [3:39 PM]
еще некоторые посты примерно двухмесячной давности (но не все!) ведут себя аналогично.

squadette [3:40 PM] 

> > > https://freefeed.net/dsumin?offset=30 а вот тут первая запись которая работает -- "Десятилетняя ....", все что до неё - тоже сосут

squadette [3:40 PM]
глючит независимо от залогиненности (edited)

squadette [3:41 PM]
ну и если дальше Сумина мотать, то там все уже не работает.

**Comment by berkus** [comment]
Fixed.

Fixed a subtle pagination issue along the way. https://github.com/pepyatka/pepyatka-server/pull/263

**Comment by smallq-git** [comment]
Verified for accounts dsumin, berkus, freefeed, support on live and on what I could find on peppa.
