### ISSUE TITLE
[Verified] Direct: realtime brings directs to recipient's subscribers.

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#563]
Pre-condition: user1 and 2 are mutuals. user2 and 3 are mutuals.
1. As user3 open user1's feed.
2. As user1 send user2 a direct message.
3. As user3 observe.

Expected: direct message is not visible to user3 anywhere.
Actual: user3 sees the message.

**Comment by smallq-git** [comment]
testuser1 sends testuser2 a direct message:
https://micropeppa.freefeed.net/testuser1/589eb437-0c56-4247-bc36-e9db821a1d95
![image](https://cloud.githubusercontent.com/assets/7983303/8583014/1ebaef70-25d3-11e5-86c9-07c9980a4ca4.png)

testo is viewing testuser1's feed and sees the direct message as it is sent:
![image](https://cloud.githubusercontent.com/assets/7983303/8583023/27428f5e-25d3-11e5-9ccc-4fe5dd183fbe.png)

Message disappears after page reload but next created direct will be visible as well.

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/023b81e90dbe76f2f65d01b32fba80bfd37affbe. Here be dragons! All real-time functions have been affected.

**Comment by smallq-git** [comment]
No longer see other people's directs!
