### ISSUE TITLE
[Verified] Mp3: file size is displayed incorrectly

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#583]
For mp3 file with size <1 mb file size is displayed incorrectly:
![image](https://cloud.githubusercontent.com/assets/7983303/8734443/abce626c-2c12-11e5-99f8-969f5ca80528.png)

**Comment by clbn** [comment]
But it still differs from the tooltip:

> <img width="712" alt="2015-07-22 11-40-48 tooltip-1" src="https://cloud.githubusercontent.com/assets/1071933/8822645/409283a8-3067-11e5-947f-68e29e7bbe41.png">
> 
> <img width="712" alt="2015-07-22 11-42-35 tooltip-2" src="https://cloud.githubusercontent.com/assets/1071933/8822646/409a0844-3067-11e5-8992-6fc0360958f2.png">

Why do we even use another calculator for it? Can't we use existing property from the tooltip?

**Comment by epicmonkey** [comment]
Nice, I have completely forgotten we have another method.

**Comment by smallq-git** [comment]
Fixed:
![image](https://cloud.githubusercontent.com/assets/7983303/9152474/ff421aa6-3e32-11e5-867b-1f003340c279.png)
