### ISSUE TITLE
Privates: security breach

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#600]
@kukutz: 
- если юзер А добавил юзера Б, пока тот был открытым 
- и юзер А держит открытым микропеппу, то последовательность действий юзера Б: 
  (1) сделать фид приватным 
  (2) написать комментарий в один из своих постов 

приведет к появлению этого комментария в ленте юзера А

**Comment by epicmonkey** [comment]
Resolved in https://github.com/pepyatka/pepyatka-server/commit/77e30f051a14647167ae7920704620dcf4e66487
