### ISSUE TITLE
[As designed] Privates: rejecting subscription request does not disallow trying again

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#602]
@kukutz: reject не запрещает юзеру А продолжать запрашивать доступ к фиду Б.

I don't remember how it was in FrF - most probably the same way.
However we can discuss how to disallow/throttle re-subscriptions short of banning User A.

**Comment by epicmonkey** [comment]
You could always ban that annoying user.

**Comment by berkus** [comment]
Agree, mechanics of allowing further subscription requests have merit - if you accidentally rejected, user should be able to request it again.
