### ISSUE TITLE
[Verified] Bans, privates: ban should automatically reject subscription request

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#603]
@kukutz: бан должен автоматически реджектить запрос. Сейчас не реджектит

**Comment by epicmonkey** [comment]
Resolved in 94bd86b208de63779b461591b9bc44c73dbfebae

**Comment by smallq-git** [comment]
Subscription is now rejected but that becomes apparent only after page reload (https://github.com/pepyatka/pepyatka-html/issues/606)
