### ISSUE TITLE
[Verified] Bans, privates: ban should disallow further subscription requests

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#604]
@kukutz: бан не мешает посылать реквесты. Если Б забанил пользователя А, то пользователю Б не должны приходить реквесты от А. Более того, сейчас Б может саппрувить запрос от А, после чего А будет видеть, что у Б нет постов (=бан).

**Comment by epicmonkey** [comment]
Resolved in f4a451fe6e2de87dd1bc715146564a27167299bc

**Comment by smallq-git** [comment]
This is fixed but Request Subscription option is still available and clickable. Request is not sent though (https://github.com/pepyatka/pepyatka-html/issues/631)
