### ISSUE TITLE
[Verified]Privates: cannot unsubscribe user from yourself

### ISSUE THREAD

**Issue by berkus** [pepyatka/pepyatka-html#605]
@kukutz: пользователь Б не может отписать от себя пользователя А, кроме как забанив-разбанив его. Если пользователь А тоже приватный, то забанить нельзя, не отписавшись от него, то есть односторонняя отписка насильно вообще невозможна.

**Comment by smallq-git** [comment]
Functionality is there. Issue to make it prettier: https://github.com/pepyatka/pepyatka-html/issues/637
