### ISSUE TITLE
Alarming error is displayed when user doesn't enter Password on Sign Up page

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#73]
If I try to sign up and forget to enter password, I am told that user with my username already exists. This could alarm people since they would expect that their usernames will be retained.

Steps:
1. Open Sign Up page.
2. Enter "Anyrandom" username.
3. Click Sign In button.

Expected: Error message: "Error: please enter password"
Actual: Error message: Error: user Anyrandom exists

**Comment by berkus** [comment]
The only exception we throw for User is "user xxx exists" for ANY validation error.

**Comment by smallq-git** [comment]
No longer reproduced: now message is displayed: "Error: Password cannot be blank"

![image](https://cloud.githubusercontent.com/assets/7983303/7228817/bdb96ce8-e765-11e4-9579-2cf4738078a2.png)
